
<div class="span3" id="sidebar">
                    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                        <li class="active">
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'customer','action'=>'manage'))?>">
                                <i class="icon-chevron-right"></i>Customer Master</a>
                        </li>
                        
<!--                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'typemaster'))?>">
                                <span class="badge badge-info pull-right"></span>
                                Material Type Master</a>
                            
                        </li>-->
                        
                </ul>
           </div>





