
<div class="span3" id="sidebar">
                    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                        <li class="active">
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'index'))?>">
                                <i class="icon-chevron-right"></i>Material Master</a>
                        </li>
                        
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'statusmaster'))?>">
                                Material Status</a>
                        </li>
                        
                        
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'groupcategorymaster'))?>">
                                Material Major Category</a>
                            
                        </li>
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'groupmaster'))?>">
                                Material Sub Category</a>
                            
                        </li>
                        
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'material','action'=>'typemaster'))?>">
                                <span class="badge badge-info pull-right"></span>
                                Material Type</a>
                            
                        </li>
                       
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'submodules','action'=>'designbase'))?>">
                                <span class="badge badge-info pull-right"></span>Design Base</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'submodules','action'=>'position'))?>">
                                <span class="badge badge-info pull-right"></span>Position Category</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'submodules','action'=>'final'))?>">
                                <span class="badge badge-info pull-right"></span>Finish Category</a>
                        </li>
                        
                </ul>
           </div>





