
<div class="span3" id="sidebar">
                    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                        <li >
                            <a href="<?=$this->url(array('module'=>'admin','controller'=>'vendor','action'=>'index'))?>">
                                <i class="icon-chevron-right"></i>Vendor Master</a>
                        </li>
                        
                        
                        
                </ul>
           </div>





