<?
if(isset($this->errorMessage)){
            echo $this->errorMessage;
}?>
      <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            <div class="navbar navbar-inner block-header">
                                <div class="muted pull-left">Registration Form</div>
                            </div>
                            <div class="block-content collapse in">
                                <div class="span12">
                                    <form name="login-form" id="login-form" method="POST" action="<?=$this->url(array('controller'=>'loginform','action'=>'logincheck'));?>">        
            <div class="form-group">
            <label class="col-md-4 col-sm-4 col-xs-12">Votre email :</label>
            <input class="col-md-4 col-sm-6 col-xs-6 form-login  input-small" type="text" placeholder="Il ne sera pas publié" id="email" name="email" required/>
		    <p class="clearfix"></p>
            </div>        
            <div class="form-group">                    
            <label class="col-md-4 col-sm-4 col-xs-12 ">Votre mot de passe :</label>
            <input class="col-md-4 col-sm-6 col-xs-6 form-login  input-small" id="password" name="password" placeholder="Your Password" required type="password" />
		    <p class="clearfix"></p>
            </div>        
<!--            <div class="text-left captcha col-md-offset-4 col-sm-offset-4 ">            
                <img src="<?php //echo $this->baseUrl();?>/public/clematix/images/recaptcha.png"> Add code from http://www.google.com/recaptcha
            </div>-->
            
            <input type="submit" id="create" name="create" value="Signin" class="btn-plein col-md-offset-0 col-sm-offset-0" style="margin-left:-25%;width:8%;"/>
         </form>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
                    </div>