
<section id="home">
    <div class="container">
      <div class="hero">
	    <img src="<?php echo $this->baseUrl();?>/public/clematix/images/logo_big.png" alt="Clematix"/>
        <hr>
        <!-- Home Slider -->
        <div class="home-slider">
          <ul class="slides">
            <li>
              <h1>The digital publishers</h1>
            </li>
          </ul>
        </div>
        <!-- End Home Slider -->               
        <hr>
        
      </div>
    </div>
  </section>
  <!-- End Home Section -->

  <!-- About Section -->  
  <section id="about" class="section">
    <div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3><strong>Qui</strong> suis-je ?</h3>
        <hr>        
      </div>
      <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-music fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>Textes, photos, videos...</h4>
                <p>Je suis composé de texte, de photos; de vidéos, de diapositivesé On me crée é partir de textesé</p>
              </div>            
            </div>            
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-book fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>On me lit partout...</h4>
                <p>On me consulte sans connexion Internet, je suis toujours proche</p>
              </div>            
            </div>
          </div>
        </div>
      </div>
      <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-suitcase fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>On méemméne partout</h4>
                <p>Je suis léger comme léair, on méemporte avec soi pour voir des clients, pour préparer une réunion, pour trouver un travail, pour réparer une machine, pour monter un meuble</p>
              </div>            
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-mobile-phone fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>...et sur tous les supports</h4>
                <p>On me regarde souvent ou parfois mais. Je me blottis dans vos smartphones pour un téte a téte. On me montre sur un écran a un auditoire.</p>
              </div>            
            </div>            
          </div>
        </div>                    
      </div>
	  <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-share fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>A partager...</h4>
                <p>On me distribueé</p>
              </div>            
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-star fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>A la pointe de la technologie</h4>
                <p>Je fais partie de cette nouvelle génération déouvrages, on méappelle un e pub3é</p>
              </div>            
            </div>            
          </div>
        </div>                    
      </div>
<!--	   About Text -->
      <p class="about-text">Ici, chez Clematixdigital, on me crée, on m'ajoute des touches différenciatrices pour méanimer, me faire vivre, bouger et parler.</p>
<!--       About Text -->
	</div>
  </section>
  <!-- End About Section -->

  <!-- How to Section -->
  <section id="howto" class="section">
<!--     Testimonials -->
    <div id="testimonials" class="parallax">
        <div class="container">
          <h2><strong>Comment</strong> me créer ?</h2>
          <hr>
<!--           Testimonials Slider    -->
          <div class="testimonials-slider animated hiding" data-animation="fadeInUp">
            <ul class="slides">
              <li>
				<p class="etape">1</p>
                <p class="client-comment">Créer votre compte</p>
                <p class="client-name">Entre les données...
				<br />Activez votre compte en cliquant sur le lien du mail que vous venez de recevoir</p>
              </li>
              <li>
				<p class="etape">2</p>
                <p class="client-comment">CHOISISSEZ-MOI PARMI LES CONFIGURATIONS PROPOSEES</p>
                <p class="client-name">Si vous méimaginez proche déune de ces configurations alors sélectionnez-la.
				<br />Au contraire, si vous avez votre propre idée de moi, alors décrivez-moi 
				<br />ou communiquez directement avec Clematixdigital, par tchat ou par mail; ils vous répondront trés vite.</p>
              </li>
			  <li>
               <p class="etape">3</p>
                <p class="client-comment">Personnalisez moi</p>
                <p class="client-name">Choisissez comment vous allez me personnaliser: ajoutez-moi des vidéos, des bandes son, des images, des diapositives...
				<br />Décrivez-moi en remplissant le formulaire ...
				<br />Envoyez vos composants, textes, photos, vidéos, bande son ... é Clematixdigital, ils les assembleront pour me créer
				<br />Le prix pour méobtenir séaffiche en bas</p>
              </li>
			  <li>
                <p class="etape">4</p>
                <p class="client-comment">Commandez moi</p>
                <p class="client-name">Vous payez 75% du montant de la commande
				<br />Au bout de quelques jours, vous me recevez; je ne suis pas encore achevé; vous pouvez commenter et apporter des modifications é mon apparence.
				<br />Clematixdigital vous propose deux allers-retours pour que je sois celui donét vous avez révé !
				<br />A tout moment, dialoguez avec clematixdigital par tchat</p>
              </li>
			  <li>
                <p class="etape">5</p>
                <p class="client-comment">Finalisez-moi</p>
                <p class="client-name">Vous méavez vu presque terminé et vous avez héte de méavoir
				<br />Il vous suffit de régler le solde et 72 heures plus tard vous méaurez</p>
              </li>
            </ul>
          </div>
           End Testimonials Slider 
		  <p class="testimonials-text"><i>Le service est disponible en ligne; vous me commandez, en quelques jours vous méavez.</i></p>
        </div>
    </div>
<!--     End Testimonials -->
    <div class="container">
		<p class="howto-text"><i>Le e-book, céest clarté, facilité, simplicité !</i></p>
    </div>
  </section>
  <!-- End How to Section -->
  
  <!-- Emerveiller Section -->
  <section id="emerveiller" class="parallax">
      <div class="container">
		<hr>
        <h4 class="center up">Emerveiller  chaque age</h4>
		<hr>
      </div>
  </section>
  <!-- End Emerveiller Section -->  
  
  <!-- Galery Section -->    
  <section id="galery" class="section">
    <div class="container">
      <div class="title col-md-8 col-sm-10 col-xs-12">
          <h3> Model <strong>Books</strong></h3>
        <hr>
        <p>J'existe sous de multiples formes; <br />vous trouverez ci-dessous quelques exemples de configuration</p>       
      </div>
        <?php for($i=0;$i<count($this->filename);$i++){ 
            $name= explode(".",$this->filename[$i]['bookname']);
            ?>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="team animated hiding" data-animation="fadeInUp" data-delay="0">
          <div class="team-photo" >
              
              <?php $name= explode(".",$this->filename[$i]['bookname']);?>
              
              <!--download id renamed from dwld to dwld-renamed 1-7-2014-->

                  <img src="<?php echo $this->baseUrl();?>/public/ebubeditor/?book=<?php echo $this->filename[$i]['newname']; ?>/<?php echo $name[0]; ?>&img" alt="" width="127" height="157">
                  
               </div>
          <div class="team-inner">
              <a href="<?php echo $this->kvUrl();?>/index.html?epub=epub_content/books/<?php echo $this->filename[$i]['newname']; ?>/<?php echo $name[0]; ?>"  id="<?php echo $name[0]; ?>" title="" class="btn-plein vimeo" >Découvrir</a>
             
              <h5 style="font-size: 20px;"><?php //$name= explode(".",$this->filename[$i]['title']);
                        echo $this->filename[$i]['title']; ?></h5>
          <p src="<?php echo $this->filename[$i]['bsize']; ?>" name="<?php $name= explode(".",$this->filename[$i]['booktitle']);echo $name[0]; ?>" id="<?php echo $this->baseUrl();?>/public/books/<?php echo $this->filename[$i]['newname']; ?>/<?php echo $this->filename[$i]['bookname']; ?>" class="fileDownloadCustomRichExperience" style="cursor:pointer;"><?php $name= explode(".",$this->filename[$i]['booktitle']);echo $name[0]; ?></p>
         
           
                     
          </div>  
             <img  name="<?php $name= explode(".",$this->filename[$i]['bookname']);echo $name[0]; ?>" id="<?php echo $this->baseUrl();?>/public/ebubeditor/?book=<?php echo $this->filename[$i]['newname']; ?>/<?php echo $name[0]; ?>&img" src="<?php echo $this->baseUrl();?>/public/clematix/images/images.jpg" alt="" width="40" height="40" style="margin-left:80%;cursor:pointer;margin-top:-55%;" class="down" book_name="<?php echo $this->kvUrl();?>/epub_content/zip/<?php echo $this->filename[$i]['newname']; ?>/<?php echo $this->filename[$i]['bookname']; ?>">
        </div>
      </div>
            
        <?php } ?>
        
        
        
        <div class="teampoto" style="display:none;">
            <p class="closepop" style="cursor: pointer;float:right;">close</p>
            <br/>    
       <center><img class="pop" src="" alt="" width="175" height="230"></center>
        <br/>
       <center> <p>Download <a name="" style="cursor: pointer;" id="" class="epubfile">.epub</a></p></center>
       <br/>   
   </div>
    </div>
      
   
      
  </section>
  <!-- End Galery Section -->
  
  
  
  <!-- Idees Section -->
  <section id="idees" class="section">
	<div class="container">
	  <!-- Clients Carousel -->
	  <div id="clients-carousel" class="owl-carousel">
        <div class="item">Novels</div>
        <div class="item">Historical Novels</div>
        <div class="item">Spiritual Books</div>
        <div class="item">Educational Books</div>
        <div class="item">Travel Magazine</div>
      </div>
      <!-- End Clients Carousel -->
	</div>
      
  </section>
  
 
  
<iframe class="iframe" style="display:none;"></iframe>
 <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.22/jquery-ui.min.js" type="text/javascript"></script>
 <link href="<?=$this->baseUrl()?>/public/assets/download.css" rel="stylesheet" type="text/css" />
 <div id="preparing-file-modal" title="Download Status" style="display: none;">
    We are downloading your file, please wait...
    <br/>
    <br/>
    <p></p>
 
    <div class="ui-progressbar-value ui-corner-left ui-corner-right" style="width: 100%; height:22px; margin-top: 20px;"></div>
</div>
    
<div id="error-modal" title="Error" style="display: none;">
    There was a problem generating your report, please try again.
</div>
        <div id="success-modal" title="Success" style="display: none;">
    Download completed.
</div>
 
 
 
 
 <style type="text/css">
     .item{
         color:#fff;font-family:'lato, Sans-serif';font-size:26px;text-align:center;
         
     }
     
     
     .ui-dialog-titlebar{
         display: none;
     }
     
     </style>
 
<script>

     $(function() {
    
    var nAgt = window.navigator.userAgent;
 
  $(".epubfile").click(function()
  { 
      $('.ui-dialog-titlebar').css({'display':'block'});
//var file = $(this).attr("id");
//file = file.split(".");
//file = file[0]+".zip";
//$(".iframe").attr("src",file); 
//exit;
  $('.teampoto').hide();
  $('.ui-dialog').hide();
      var name=$(this).attr("name");
      var size=$(this).attr("src");
     
    $("#galery").css({"opacity":"0.6"});
    $("div#preparing-file-modal>p").text('');
    $("#preparing-file-modal").dialog();
 //$('div#preparing-file-modal').text('Downloading...');
    var url=$(this).attr("id");
 
    var anchor = document.createElement('a');
    anchor.setAttribute('href', url);
    anchor.setAttribute('download', name +'.epub');
    if((nAgt.indexOf("Chrome"))!=-1)
    {
    $(anchor)[0].click();
   
    //anchor.dispatchEvent(ev);
    }
    else if ((nAgt.indexOf("Firefox"))!=-1)
    {
    var ev = document.createEvent("MouseEvents");
    ev.initMouseEvent("click", true, false, self, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    anchor.dispatchEvent(ev);
   
    }
    else
    {
         //$(anchor)[0].click();
     $(".iframe").attr("src",url);
    
    }
    var oReq = new XMLHttpRequest();

    oReq.addEventListener("progress", updateProgress, false);
    oReq.addEventListener("load", transferComplete, false);
    oReq.addEventListener("error", transferFailed, false);
    oReq.addEventListener("abort", transferCanceled, false);
    oReq.open("POST", url + ((/\?/).test(url) ? "&" : "?") + (new Date()).getTime(), true);
    oReq.setRequestHeader("Content-Type", "application/epub+zip");
    oReq.responseType = "blob";
    //oReq.open();
    oReq.send(null);
    // ...

    // progress on transfers from the server to the client (downloads)
    function updateProgress (oEvent) {

        console.log(oEvent);
        if (oEvent.lengthComputable) {
  
         var percentComplete = oEvent.loaded / oEvent.total *100;

        //$('div#preparing-file-modal').html('');
        
        $("div#preparing-file-modal").text('Downloading '+ percentComplete.toFixed(2) + "%");
  }   else {
    
    $("div#preparing-file-modal").text('Downloading...');
  }
}

    function transferComplete(evt) 
         {
            setTimeout(function(){$('#preparing-file-modal').dialog('close')}, 2000);
            setTimeout(function(){$('.ui-dialog').html('')},2000);
            setTimeout(function(){$("#galery").css({"opacity":"1"})}, 2000);
      
     //$preparingFileModal.dialog('close');
     //$preparingFileModal.dialog('close');
        }

        function transferFailed(evt) {

          //alert("An error occurred while transferring the file.");
        }

        function transferCanceled(evt) {
          //alert("The transfer has been canceled by the user.");
        }



         }); });
     
     
</script>
  
  <script>
      $(function()
      {
          $(".down").click(function(){
              var pop=$(this).attr("id");
              
            $('.teampoto').show();
            $('.ui-dialog').show();
            
           
            $("#preparing-file-modal").hide();
            $(".epubfile").attr("id",$(this).attr("book_name"));
            $(".epubfile").attr("name",$(this).attr("name"));
            
           //$("#dwld").trigger("click");
           //$(".fileDownloadCustomRichExperience").trigger("click");
          
           $(".pop").attr("src",pop); 
           
           $(".teampoto").dialog();
        //            $(".ui-dialog-titlebar").css({"display":"none",});
        //            $(".ui-resizable").css({"top":"0"});
                    
      });
      $(".closepop").click(function(){
      $(".teampoto").dialog('close');
      });
      
  });
  
      
      //$(".iframe").colorbox({iframe:true, width:"100%", height:"100%"});
      $(".vimeo").colorbox({iframe:true, width:"90%", height:"90%"});
           </script>
           
           
           
   