
<section id="home">
    <div class="container">
      <div class="hero">
	    <img src="<?php echo $this->baseUrl();?>/public/clematix/images/logo_big.png" alt="Clematix"/>
        <hr>
        <!-- Home Slider -->
        <div class="home-slider">
          <ul class="slides">
            <li>
              <h1>Clematixdigital est un environnement<br /> de création d’ouvrages numériques</h1>
            </li>
          </ul>
        </div>
        <!-- End Home Slider -->               
        <hr>
        
      </div>
    </div>
  </section>
  <!-- End Home Section -->

  <!-- About Section -->  
  <section id="about" class="section">
    <div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3><strong>Qui</strong> suis-je ?</h3>
        <hr>        
      </div>
      <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-music fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>Textes, photos, videos...</h4>
                <p>Je suis composé de texte, de photos; de vidéos, de diapositivesé On me crée é partir de textesé</p>
              </div>            
            </div>            
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-book fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>On me lit partout...</h4>
                <p>On me consulte sans connexion Internet, je suis toujours proche</p>
              </div>            
            </div>
          </div>
        </div>
      </div>
      <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-suitcase fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>On méemméne partout</h4>
                <p>Je suis léger comme léair, on méemporte avec soi pour voir des clients, pour préparer une réunion, pour trouver un travail, pour réparer une machine, pour monter un meuble</p>
              </div>            
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-mobile-phone fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>...et sur tous les supports</h4>
                <p>On me regarde souvent ou parfois mais. Je me blottis dans vos smartphones pour un téte a téte. On me montre sur un écran a un auditoire.</p>
              </div>            
            </div>            
          </div>
        </div>                    
      </div>
	  <div class="promo-line">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo right animated hiding" data-animation="fadeInLeft">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-share fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>A partager...</h4>
                <p>On me distribueé</p>
              </div>            
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="row">
            <div class="promo animated hiding" data-animation="fadeInRight">
              <div class="col-md-2 col-sm-3 promo-icon-box">
                <div class="promo-icon">
                  <i class="fa fa-star fa-2x"></i>
                </div>
              </div>
              <div class="col-md-10 col-sm-9">
                <h4>A la pointe de la technologie</h4>
                <p>Je fais partie de cette nouvelle génération déouvrages, on méappelle un e pub3é</p>
              </div>            
            </div>            
          </div>
        </div>                    
      </div>
	  <!-- About Text -->
      <p class="about-text">Ici, chez Clematixdigital, on me crée, on m'ajoute des touches différenciatrices pour méanimer, me faire vivre, bouger et parler.</p>
      <!-- About Text -->
	</div>
  </section>
  <!-- End About Section -->

  <!-- How to Section -->
  <section id="howto" class="section">
    <!-- Testimonials -->
    <div id="testimonials" class="parallax">
        <div class="container">
          <h2><strong>Comment</strong> me créer ?</h2>
          <hr>
          <!-- Testimonials Slider -->   
          <div class="testimonials-slider animated hiding" data-animation="fadeInUp">
            <ul class="slides">
              <li>
				<p class="etape">1</p>
                <p class="client-comment">Créer votre compte</p>
                <p class="client-name">Entre les données...
				<br />Activez votre compte en cliquant sur le lien du mail que vous venez de recevoir</p>
              </li>
              <li>
				<p class="etape">2</p>
                <p class="client-comment">CHOISISSEZ-MOI PARMI LES CONFIGURATIONS PROPOSEES</p>
                <p class="client-name">Si vous méimaginez proche déune de ces configurations alors sélectionnez-la.
				<br />Au contraire, si vous avez votre propre idée de moi, alors décrivez-moi 
				<br />ou communiquez directement avec Clematixdigital, par tchat ou par mail; ils vous répondront trés vite.</p>
              </li>
			  <li>
               <p class="etape">3</p>
                <p class="client-comment">Personnalisez moi</p>
                <p class="client-name">Choisissez comment vous allez me personnaliser: ajoutez-moi des vidéos, des bandes son, des images, des diapositives...
				<br />Décrivez-moi en remplissant le formulaire ...
				<br />Envoyez vos composants, textes, photos, vidéos, bande son ... é Clematixdigital, ils les assembleront pour me créer
				<br />Le prix pour méobtenir séaffiche en bas</p>
              </li>
			  <li>
                <p class="etape">4</p>
                <p class="client-comment">Commandez moi</p>
                <p class="client-name">Vous payez 75% du montant de la commande
				<br />Au bout de quelques jours, vous me recevez; je ne suis pas encore achevé; vous pouvez commenter et apporter des modifications é mon apparence.
				<br />Clematixdigital vous propose deux allers-retours pour que je sois celui donét vous avez révé !
				<br />A tout moment, dialoguez avec clematixdigital par tchat</p>
              </li>
			  <li>
                <p class="etape">5</p>
                <p class="client-comment">Finalisez-moi</p>
                <p class="client-name">Vous méavez vu presque terminé et vous avez héte de méavoir
				<br />Il vous suffit de régler le solde et 72 heures plus tard vous méaurez</p>
              </li>
            </ul>
          </div>
          <!-- End Testimonials Slider -->
		  <p class="testimonials-text"><i>Le service est disponible en ligne; vous me commandez, en quelques jours vous méavez.</i></p>
        </div>
    </div>
    <!-- End Testimonials -->
    <div class="container">
		<p class="howto-text"><i>Le e-book, céest clarté, facilité, simplicité !</i></p>
    </div>
  </section>
  <!-- End How to Section -->
  
  <!-- Emerveiller Section -->
  <section id="emerveiller" class="parallax">
      <div class="container">
		<hr>
        <h4 class="center up">Emerveiller é chaque age</h4>
		<hr>
      </div>
  </section>
  <!-- End Emerveiller Section -->  
  
  <!-- Galery Section -->    
  <section id="galery" class="section">
    <div class="container">
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3>Derniers <strong>modéles</strong></h3>
        <hr>
        <p>Jéexiste sous de multiples formes; <br />vous trouverez ci-dessous quelques exemples de configuration</p>       
      </div>
        <?php for($i=0;$i<count($this->filename);$i++){ ?>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="team animated hiding" data-animation="fadeInUp" data-delay="0">
          <div class="team-photo">
              <img src="<?php echo $this->baseUrl();?>/public/cover_image/<?php echo $this->filename[$i]['coverimage']; ?>" alt="" width="127" height="157">
          </div>
          <div class="team-inner">
              <a href="#" id="<?php echo $this->baseUrl();?>/public/ebookviewer/<?php $name= explode(".",$this->filename[$i]['bookname']);echo $name[0]; ?>" title="" class="btn-plein vimeo open_book">Découvrir</a>
                        <h5 style="font-size: 20px;"><?php //$name= explode(".",$this->filename[$i]['title']);
                        echo $this->filename[$i]['title']; ?></h5>
            <p><?php $name= explode(".",$this->filename[$i]['booktitle']);echo $name[0]; ?></p>
          </div>          
        </div>
      </div>
        <?php } ?>
        
        

    </div>
      

      
      
      
      
      
      
      
  </section>
  <!-- End Galery Section -->
  
  <!-- Idees Section -->
  <section id="idees" class="section">
	<div class="container">
	  <!-- Clients Carousel -->
	  <div id="clients-carousel" class="owl-carousel">
        <div class="item"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/exemples/logo1.png" alt=""></div>
        <div class="item"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/exemples/logo2.png" alt=""></div>
        <div class="item"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/exemples/logo3.png" alt=""></div>
        <div class="item"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/exemples/logo4.png" alt=""></div>
        <div class="item"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/exemples/logo5.png" alt=""></div>
      </div>
      <!-- End Clients Carousel -->
	</div>
  </section>
  
  <script src="<?php echo $this->baseUrl();?>/public/js/jquery.colorbox.js"></script>
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>-->
  <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/colorbox.css" />
  <script>
			$(function(){
				$(".vimeo").click(function(e)
                                {
                                url = "<?php echo $this->baseUrl();?>/ebook/index";
                                $.ajax({
                                type: "POST",
                                url: url,
                                data: 'id=colombe.html', // serializes the form's elements.
                                success: function(returndata)
                                {
                                    $(".vimeo").colorbox({iframe:true, innerWidth:1200, innerHeight:650});
                                    
                                }
                           });
   
				//$(".iframe").colorbox({iframe:true, width:"100%", height:"100%"});
				//$(".vimeo").colorbox({iframe:true, innerWidth:1200, innerHeight:710});
			}); });
		</script>