
  
<!-- Mon compte Section -->
  <section id="login" class="section">
	<div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3><strong>Créez</strong> votre compte</h3>
		<p>Lorem ipsum dolor sit amet</p>
        <hr>       
      </div>
	  <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="service animated hiding" data-animation="fadeInUp" data-delay="0">
           <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-2x fa-stack-2x"></i>
            <i class="fa fa-trophy fa-stack-1x service-icon"></i>
          </span>
		  <h3>Renseignez les informations ci-dessous</h3>
                  <div class="row-fluid">
                        <div class="span3" id="content" style="display:none;width: 50%;margin-left: 33.5%;margin-bottom: -20px;">
                        <div class="alert alert-success">	
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <div id="kumar">
                        	</div></div></div></div>
		    <br>
            <form name="signup-form" id="signup-form" method="POST" action="<?=$this->url(array('controller'=>'signupform','action'=>'index'));?>">        
            <div class="form-group">
               
            <input class="col-md-4 col-sm-4 col-xs-12 col-md-offset-4 form-login input-small" type="text" placeholder="User Name" id="uname" name="uname" required/>
            <p class="clearfix"></p>
            </div>
            <div class="form-group">
           
            <input class="col-md-4 col-sm-6 col-xs-12 col-md-offset-4 form-login input-small" type="text" placeholder="Your Email" id="email" name="email" required/>
		    <p class="clearfix"></p>
            </div>        
            <div class="form-group">                    
           
            <input class="col-md-4 col-sm-6 col-xs-12 col-md-offset-4 form-login input-small" id="password" name="password" placeholder="Password (Min - 6 chars" required type="password" />
		    <p class="clearfix"></p>
            </div>        
            <div class="form-group">                    
            
            <input class="col-md-4 col-sm-6 col-xs-12 col-md-offset-4 form-login input-small" id="confirmpassword" name="confirmpassword" placeholder="Confirm Password" required type="password"/>
		    <p class="clearfix"></p>
            </div>   
                
                <div class="form-group">                    
            
            <input class="col-md-4 col-sm-6 col-xs-12 col-md-offset-4 form-login input-small" id="contactno" name="contactno" placeholder="Your Contact Number" required type="text"/>
		    <p class="clearfix"></p>
            </div>  
            
            <div class="text-left captcha col-md-offset-4 col-sm-offset-4 ">            
                <div id="recaptcha_div"> 
                    <?php echo $this->recaptcha;?>
                    
                </div>

            <p class="clearfix"></p>
            <div class="form-group">                    
            <div class="text-left">            
                <input type="checkbox" id="IdCheckBox" value="Y" name="odcn" id="odcn"/> 
                <label for="IdCheckBox" class="check-box">Email me offers, discount, coupon and news</label>
            </div>
            </div>    
                                    
            <div class="text-left">       
                <div class="form-group">
                <input type="checkbox" id="IdCheckBox" value="valeur" id="agree" name="agree"/> 
                <label for="IdCheckBox" class="check-box">I agree to the <a href="">Terms and Conditions</a></label>
                </div>
            </div>     
            <p class="clearfix"></p>
            <input type="submit" id="create" name="create" value="Sign Up" class="btn-plein" />
            <input type="reset" id="cancel" name="cancel" value="Cancel" class="btn-trait"/>
         </form>  
                    
                     
        </div>
            <div id="sign-log" style="display:none;">Click to&#160;&#160;&#160;<a href="<?php echo $this->baseUrl();?>/loginform">Login</a></div>
      </div>
             
	 </div>
  </section>
  <!-- End Bureaux Section -->