 
 <script type="text/javascript">
     
   $(document).ready(function(){
       
        
       $(document).on("click", ".addstatus", function(){
           $('#type_form')[0].reset();
            $('#id').val('');
           $('#save_button').removeClass("hidden");
           $('.inputDisabled').removeAttr("readonly");
           $('#button_div').addClass("span7").removeClass("span9");
       });
       
           
             $(document).on("click", ".editdesign", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
             $('#mask').show();
            $('.contenttab').html("Edit Design Base");
           var dataString ='&type=gettype&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'submodules','action'=>'getdesignbase'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v);  
                              if(k!='desc'){
                                  $('#'+k).attr("readonly",true);   
                              }
                    });
                    $('#mask').hide();
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
    
   
            $(document).on("click", ".viewdesign", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
             $('#mask').show();
            $('.contenttab').html("View Design Base");
           var dataString ='&type=getgroup&id='+id;
            // alert(dataString);
            $('#save_button').addClass("hidden");
            $('#button_div').addClass("span9").removeClass("span7");
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'submodules','action'=>'getdesignbase'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v);  
                                   $('#'+k).attr("readonly",true); 
                                //$('#deptregister').val("Back");   
                               });
                               $('#mask').hide();
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
         
         $(document).on("click", ".listtab", function(){
            $('.contenttab').html("Add New Design Base");
         });
         
    $(document).on("click", ".imgswap", function(){
         var id = $(this).attr("id");
         var vendor_id = id.split("_"); 
         
            if ($(this).attr("class") == "imgswap") {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
                this.src = this.src.replace("_off", "_on");
                var status = '1';
            } else {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
                this.src = this.src.replace("_on", "_off");
                var status = '0';
            }
            $(this).toggleClass("on");
            
             var dataString ='&type=changestatusdesign&id='+vendor_id[1]+'&status='+status;
           // alert(dataString)
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'submodules','action'=>'changestatusdesign'))?>',
                        data: dataString,
                success: function(j) {
                    alert(result);
                    //$('div#addstatus').html(result);
                }
            });
             });
            
     $( "#type_form" ).submit(function( event ) {
            var type = $('#type').val();
            var type = type.trim();
            var code = $('#code').val();
            var code = code.trim();
            
            if(type == ''){
               $('#type').focus();
               return false;
            }
            if(code == ''){
               $('#code').focus();
               return false;
            }
           
            
     });
     
     
     });
 </script>
 <?php echo $this->render('materiallist.phtml');  ?> 

<div class="span9" id="content">
    
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Design Base</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#materiallist" class="listtab">Design Base List</a></li>
  <li class="addstatus"><a href="#addstatus" class="contenttab">Add New Design Base</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="materiallist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>Design Base</th>
                                                <th>Code</th>
                                                <th>Action</th>
<!--                                                <th>Status</th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->designbase as $value) { ?>
                                            <tr><td><?php echo $value[designbase] ?></td>
                                                <td><?php echo $value[code] ?></td>
                                                <td>
                                                    <a  class="viewdesign" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo ' VIEW'; ?></a>
                                                    <a  class="editdesign" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a>
<!--                                                    <a href="<?php echo $this->baseUrl();?>/admin/submodules/deletedesign/delete/<?php echo $value[id]; ?>" class="book_delete" style="cursor:pointer;"><?php echo '/ DEL '; ?></a>-->
                                                
                                                </td>
<!--                                                <td> <?php if($value[status] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php }  if($value[status] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                <?php } ?>
                                                </td>-->
                                                
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addstatus">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'submodules','action'=>'savedesignbase'))?>" method="post" id="designbase_form">
        <input type="hidden" name="id" id="id" class="inputDisabled">
          
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="designbase" class="required">Design Base:</label></div>
              <div class="form-right pull-left"><input type="text" name="designbase" id="designbase" value="" class="form-control inputDisabled" required="true" onkeypress="return isAlpha(event)" maxlength="20"></div>
          </div>
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="code" class="required">Code:</label></div>
              <div class="form-right pull-left"><input type="text" name="code" id="code" value="" class="form-control inputDisabled" required="true" onkeypress="return isAlpha(event)"  maxlength="1"></div>
          </div>
        <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="desc" >Description:</label></div>
              <div class="form-right pull-left">
                  <textarea name="desc" id="desc" rows='3' cols='5'></textarea>
              </div>
          </div>
        
        

        <div id="button_div" class="clearfix span7" style="float: right;" >
<div class="span2" id="save_button">
 <input class='btn btn-primary' type="submit" name="deptregister" id="deptregister" value="Save" class="btn btn-default" />
</div>
 
<div class="span1" id="back_button">
    <a href="/../asteria/admin/submodules/designbase"><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
</div>
      </div>
  </form>
  </div>
  
  
</div>
 
<script>
  $(function () {
      $('#myTab a[href="#<?php echo $this->showid;?>"]').tab('show');
    $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
  })
</script>   
                                     
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   

    

</div>




