<script type="text/javascript" charset="utf-8">
                        
                        jQuery(document).ready(function () {
$(document).on('click', '.adddept', function(event) {

     jQuery("#register_dept").attr("value", "add");
     jQuery('#reset_dept').trigger('click');
});
$(document).on('click', '.adddesign', function(event) {
//jQuery('.adddesign').click(function () {
     jQuery("#register_design").attr("value", "add");
     jQuery('#reset_design').trigger('click');
});
$(document).on('click', '.viewdesigntab', function(event) {
//jQuery('.viewdesigntab').click(function () {
     jQuery('.adddept').html('Add Department');
      jQuery('.adddesign').html('Add Designation');
      jQuery('#reset_design').trigger('click');
       jQuery('#reset_dept').trigger('click');
});
$(document).on('click', '.viewdepttab', function(event) {
//jQuery('.viewdepttab').click(function () {
     jQuery('.adddept').html('Add Department');
      jQuery('.adddesign').html('Add Designation');
      jQuery('#reset_design').trigger('click');
       jQuery('#reset_dept').trigger('click');
});
$(document).on('click', '.edit_dept', function(event) {
     jQuery('#mask').show();
//        jQuery('.edit_dept').click(function () {
            jQuery('.adddept').html('Edit Department');
            jQuery('#myTab a[href="#adddept"]').tab('show');
            var id = jQuery(this).attr("id");
            jQuery("#register_dept").attr("value", "update");
            var dataString = '&edit_department=' + id;
            jQuery.ajax({
                type: "POST",
                url: '<?= $this->url(array('controller' => 'auth', 'action' => 'addgroupdept')) ?>',
                data: dataString,
                success: function (j) {

                    var json = jQuery.parseJSON(j);

                    jQuery(json).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery('.dept_' + k).val(v);
                        });
                    });
 jQuery('#mask').hide();
                }
            });
        });

$(document).on('click', '.edit_designation', function(event) {
//jQuery('.edit_designation').click(function () {
 jQuery('#mask').show();
            jQuery('.adddesign').html('Edit Designation');
            jQuery('#myTab a[href="#adddesign"]').tab('show');
            var id = jQuery(this).attr("id");
            jQuery("#register_design").attr("value", "update");
            var dataString = '&edit_designation=' + id;
            jQuery.ajax({
                type: "POST",
                url: '<?= $this->url(array('controller' => 'auth', 'action' => 'addgroupdept')) ?>',
                data: dataString,
                success: function (j) {

                    var json = jQuery.parseJSON(j);


                    jQuery(json).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery('.design_' + k).val(v);
                        });
                    });
 jQuery('#mask').hide();
                }
            });
        });
        
        $(document).on('click', '.delete', function(event) {
//        jQuery('.delete').click(function () {
     if(confirm("Are you sure you want to delete this?")){
     }
    else{
        return false;
    }
});

 $(document).on("click", "tbody tr td .imgswap", function() {
        var id = $(this).attr("id");
        var so_id = id.split("_");
      
        if ($(this).attr("class") == "imgswap") {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
            this.src = this.src.replace("_off", "_on");
            var status = '1';
        } else {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
            this.src = this.src.replace("_on", "_off");
            var status = '0';
        }
        $(this).toggleClass("on");

        var dataString = '&type=changestatus&id=' + so_id[1] + '&status=' + status;

        $.ajax({
            type: "POST",
            url: '<?=$this->url(array('controller'=>'auth','action'=>'changegroupstatus'))?>',
            data: dataString,
            success: function(j) {
      
                
            }
    });
    });
    
     $(document).on("click", "tbody tr td .imgswap1", function() {
        var id = $(this).attr("id");
        var so_id = id.split("_");
      
        if ($(this).attr("class") == "imgswap1") {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
            this.src = this.src.replace("_off", "_on");
            var status = '1';
        } else {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
            this.src = this.src.replace("_on", "_off");
            var status = '0';
        }
        $(this).toggleClass("on");

        var dataString = '&type=changestatus&id=' + so_id[1] + '&status=' + status;

        $.ajax({
            type: "POST",
            url: '<?=$this->url(array('controller'=>'auth','action'=>'changedeptstatus'))?>',
            data: dataString,
            success: function(j) {
      
                
            }
        });
    });

    });
</script>
<?php echo $this->render('navebar/leftnavbar.phtml'); ?>

<div class="span9" id="content">
     <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
                    	
    
     <!--DELETE BOOK-->
    <div id="accordion">
        
    <div class="row-fluid">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Department and Designation</div>
                                    
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
     <?php if($this->permission['view']==1){ ?>
                                  <ul class="nav nav-tabs" id="myTab">
  
  <li class="active"><a href="#viewdept" class="viewdepttab">View Department</a></li>
  <?php if($this->permission['create']==1){ ?>
  <li ><a href="#adddept" class="adddept">Add Department</a></li>
  <?php }?>
  
  <li><a href="#viewgorup" class="viewdesigntab">view Designation</a></li>
  <?php if($this->permission['create']==1){ ?>
  <li><a href="#adddesign" class="adddesign">Add Designation</a></li>
  <?php } ?>
</ul>
 
<div class="tab-content">
  <div class="tab-pane " id="adddept">
      <form enctype="application/x-www-form-urlencoded" action="<?= $this->url(array('controller' => 'auth', 'action' => 'addgroupdept')) ?>" method="post" name="">
       <input type="hidden" name="deptid" id="deptid" class="dept_id" value="" >

          <div class="formvalue">
              <div class="form-left pull-left">
                  <label for="department" class="required">Department Name:</label>
              </div>
              <div class="form-right pull-left">
                  <input type="text" name="department" id="department" value="" onkeypress="return isAlphaSpace(event)" class="form-control dept_name" required="true" /></dd>
              </div>
          </div>

          <div class="formvalue">
              <div class="form-left pull-left">
                  &nbsp;
              </div>
              <div class="form-right pull-left">
                  <input class='btn btn-primary' type="submit" name="register_dept" onkeypress="return isAlphaSpace(event)" id="register_dept" value="add" class="btn btn-default" required="true"/>
              </div>
              <div style="display:none;"><button type="reset" id="reset_dept" value="Reset"></button></div>
          </div>


      </form>
  </div>
    
    
  <div class="tab-pane active" id="viewdept">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th style="width:50px;">SI No</th>
                                                <th>Department Name</th>
                                                <th>Action</th>
                                                 <th>Status</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $i=1; foreach($this->deptList as $deptlist){ ?>
                                            <tr><td><?=$i++;?></td>
                                                <td><?=$deptlist['name']?></td>
                                                
                                                
                                                <td style="width:200px;">
<!--                                                    <a class="delete" href="<?php echo $this->baseUrl(); ?>/admin/auth/addgroupdept/delete_dept_id/<?=$deptlist['id']?>" >
                                                        <?php echo 'DEL '; ?></a>-->
                                                     <?php if($this->permission['edit']==1){ ?>
                                                    <a href="#" class="edit_dept" id="<?=$deptlist['id']?>">
                                                <?php echo ' EDIT'; ?></a>
                                                     <?php }?>
                                                </td>
                                                <td>
                                                    <?php if($deptlist['status'] == '0'){ ?>
                                                    <a   style="cursor:pointer;">
                                                    <img class="imgswap1" id="approval_<?php echo $deptlist['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    </a>
                                                    <?php }  if($deptlist['status'] == '1'){ ?>
                                        <a   style="cursor:pointer;">
                                                    <img class="imgswap1 on" id="approval_<?php echo $deptlist['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                        </a>
                                                <?php } ?>
                                                </td>
                                           
                                            </tr>
                                            <?php }?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
      
      </div>
  <div class="tab-pane" id="adddesign">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'auth','action'=>'addgroupdept'))?>" method="post" name="">
                   <input type="hidden" name="design" id="design" class="design_id" value="" >
                            
<div class="formvalue">
    <div class="form-left pull-left">
        <label for="firstname" class="required">Designation Name:</label>
    </div>
<div class="form-right pull-left">
    <input type="text" name="group" id="group" value="" maxlength="40" onkeypress="return isAlphaSpace(event)" class="form-control design_name" required="true">
</div>
</div>

<div class="formvalue">
    <div class="form-left pull-left">
        &nbsp;
</div>
    <div class="form-right pull-left">
<input class='btn btn-primary' type="submit" maxlength="40" name="register_design" id="register_design" value="add" class="btn btn-default" />
</div>
    <div style="display:none;"><button type="reset" id="reset_design" value="Reset"></button></div>
</div>

</form></div>
  <div class="tab-pane" id="viewgorup">
      
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example1">
                                        <thead>
                                            <tr>
                                                <th style="width:50px;">SI No</th>
                                                <th>Group Name</th>
                                                <th>Action</th>
                                                <th>Status</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $i=1; foreach($this->groupList as $grouplist){ ?>
                                            <tr><td><?=$i++;?></td>
                                                <td><?=$grouplist['name']?></td>
                                                
                                                
                                                <td style="width:200px;">
<!--                                                    <a class="delete" href="<?php echo $this->baseUrl(); ?>/admin/auth/addgroupdept/delete_designation_id/<?=$grouplist['id']?>" >
                                                        <?php echo 'DEL '; ?></a>-->
                                                     <?php if($this->permission['edit']==1){ ?>
                                                    <a href="#" class="edit_designation" id="<?=$grouplist['id']?>">
                                                <?php echo ' EDIT'; ?></a>
                                                     <?php }?>
                                                </td>
                                                
                                                <td>
                                                    <?php if($grouplist['status'] == '0'){ ?>
                                                    <a   style="cursor:pointer;">
                                                    <img class="imgswap" id="approval_<?php echo $grouplist['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    </a>
                                                    <?php }  if($grouplist['status'] == '1'){ ?>
                                        <a   style="cursor:pointer;">
                                                    <img class="imgswap on" id="approval_<?php echo $grouplist['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                        </a>
                                                <?php } ?>
                                                </td>
                                                
                                            <?php }?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  
  </div>
</div>
 
       <?php } else  { echo 'You are not authorized person to access this module'; } ?>                                
                                
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
    <!--END-->
    
      
    
    

    
</div>
</div>




