<div class="container" id="login">
      <h2><?php //echo 'Enter Email';?>
      <?php echo $this->errorMessage; ?></h2>
                            <form class="form-signin" action="<?=$this->url(array('controller'=>'auth','action'=>'forgotpassword'));?>"
								  name="recover password"
								  id="pass_recover"
								  
								  method="post">

<h3 class="form-signin-heading">Enter registered e-mail</h3>
                        <div class="clearfix">
                            <label for="passw"><?php echo 'Email';?><sup>*</sup></label>
                            <div class="input">
                                <input type="email" name="email" id="email" value="" placeholder="Enter Your Email" required="true">
                            </div>
                        </div>
                        
                        <div class="clearfix">
	                        <div class="input">
                                    <input class='btn btn-primary' type="submit" value="submit">
	                        </div>
                        </div>
                    </form>
</div>