<script type="text/javascript">

    $(document).ready(function() {

        $('#mail-form').submit(function(e)
        {
            var msg = '';
            mail_server = $('input#mail_server').val();
            mail_port = $('input#mail_port').val();
            mail_username = $('input#mail_username').val();
            mail_password = $('input#mail_password').val();
            admin_mail = $('input#admin_mail').val();
            contact_mail = $('input#contact_mail').val();
            //alert(empty);
            if (mail_server == '')
            {
                $('input').removeClass('highlight');
                $('#mail_server').focus();
                msg = 'Please enter a valid mail server';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                return false;
            } else {
                var pattern = /^([a-zA-Z0-9_.-])+\.([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
                if (!(pattern.test(mail_server)))
                {

                    $('#mail_server').focus();
                    msg = 'Please enter a valid mail server';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                    return false;

                }
            }
            if (mail_port == '')
            {
                $('input').removeClass('highlight');
                $('#mail_port').focus();
                msg = 'Please enter digits';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                return false;
            } else {
                var pattern = /^\d{3}$/;
                if (!(pattern.test(mail_port)))
                {

                    $('#mail_port').focus();
                     msg = 'Please enter only three digits';
                     $('#error').css('display','block');
                        $('#error').html(msg).fadeIn(2000);

                    return false;
                }

            }
            if (mail_username == '')
            {

                $('#mail_username').focus();
                msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                return false;
            } else {
                var pattern = /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
                if (!(pattern.test(mail_username)))
                {

                    $('#mail_username').focus();
                     msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                    return false;

                }

            }
            if (mail_password == '')
            {

                $('#mail_password').focus();
                return false;
            }
            if (admin_mail == '')
            {
                $('input').removeClass('highlight');
                $('#admin_mail').focus();
                 msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                return false;
            } else {
                var pattern = /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
                if (!(pattern.test(admin_mail)))
                {

                    $('#admin_mail').focus();
                     msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);

                    return false;

                }

            }
            if (contact_mail == '')
            {

                $('#contact_mail').focus();
                 msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);
                return false;
            } else {
                var pattern = /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
                if (!(pattern.test(contact_mail)))
                {

                    $('#contact_mail').focus();
                     msg = 'Please enter a valid mail address';
                   // alert(msg);
                    $('div#diverr').css('display','block');
                        $('#error').html(msg).fadeIn(2000);

                    return false;

                }

            }



        });
    });
</script>


<div class="row">




    <div class="span9" id="content">
        <div class="row-fluid">
           
                <div id='diverr' class="alert alert-error" style='display:none;'>
                    <button class="close" data-dismiss="alert">&times;</button>
                    <strong  id="error" ></strong> .
                </div>        

            <div class="navbar">
                <div class="navbar-inner">
                    <ul class="breadcrumb">
                        <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
                        <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
                        <li>
                            <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'auth', 'action' => 'home')) ?>">Dashboard</a> <span class="divider">/</span>	
                        </li>

                        <li class="active">Mail Config</li>
                    </ul>
                </div>
            </div>
        </div>



        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Mail</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <form action="" id="mail-form" class="form-horizontal" method="post" >
                            <fieldset>
                                <legend>Config mail</legend>

                                <div class="control-group">
                                    <label class="control-label" for="date01">Mail server</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="mail_server" name="mail_server" value="<?=$this->mailconfig[0]['mail_server']?>" placeholder="mail server">

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="select01">Mail port</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="mail_port" name="mail_port" value="<?=$this->mailconfig[0]['mail_port']?>" placeholder="mail port">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="select01">Mail Username</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="mail_username" name="mail_username" value="<?=$this->mailconfig[0]['mail_username']?>" placeholder="mail_username">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="select01">Mail Password</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="mail_password" name="mail_password" value="<?=$this->mailconfig[0]['mail_password']?>" placeholder="mail password">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="select01">Admin mail</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="admin_mail" name="admin_mail" value="<?=$this->mailconfig[0]['admin_mail']?>" placeholder="Admin mail">

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="select01">Contact Mail</label>
                                    <div class="controls">

                                        <input type="text" class="input-xlarge" id="contact_mail" name="contact_mail" value="<?=$this->mailconfig[0]['contact_mail']?>" placeholder="contact mail">

                                    </div>
                                </div>


                                <div class="form-actions">
                                    <input type="hidden" name="id" value="<?= $this->values->id ?>">
                                    <button type="submit" class="btn btn-primary" name="Submit">Save changes</button>
                                    <button type="reset" class="btn">Cancel</button>
                                </div>
                            </fieldset>
                        </form>

                    </div>
                </div>
            </div>
            <!-- /block -->
        </div>




    </div>



