 <div class="container" id="login">
      <h2><?php //echo 'Enter Email';?>
      <?php echo $this->errorMessage; ?></h2>

                            <form class="form-signin" action="<?=$this->url(array('controller'=>'auth','action'=>'recoverpassword'));?>"
								  name="recover password"
								  id="pass_recover"								  
								  method="post">
<h3 class="form-signin-heading">Enter new password</h3>
<input type="hidden" name="hashid" value="<?php echo $this->hash;?>">
                        <div class="clearfix">
                            <label for="passw"><?php echo 'Password';?><sup>*</sup></label>
                            <div class="input">
                                <input type="password" name="password" id="password" value="" placeholder="Enter New password" required="true">
                            </div>
                        </div>
                        
                        <div class="clearfix">
                            <label for="passw"><?php echo 'Confirm Password';?><sup>*</sup></label>
	                        <div class="input">
                                <input type="password" name="repassword" id="repassword" value="" placeholder="Re Enter New password" required="true">
	                        </div>
                        </div>
                                <div class="clearfix">
	                        <div class="input">
                                    <input class='btn btn-primary' type="submit" value="submit">
	                        </div>
                        </div>
                    </form>
 </div>
<?php if(isset($this->redirect))
    {echo '<script>setTimeout(function(){ window.location = "'.$this->baseUrl().'/admin/auth/login'.'"}, 5000);</script>';}
            ?>

