


<script type="text/javascript">


function CheckForm() {
          var inputElems = document.getElementsByClassName("permission_role"),
count = 0;
var msg='Please Select Functions and Roles before Save';
for (var i=0; i<inputElems.length; i++) {
            if (inputElems[i].type === "checkbox" && inputElems[i].checked === true)
            {
                count++;
            }
        }
        if(count<3){
            alert(msg);
            return false;
            
        }
         return true;
    }

    jQuery(document).ready(function () {



        jQuery('.addrole').click(function () {
           
            jQuery("#register").attr("value", "add");
            jQuery('#reset').trigger('click');
        });


        jQuery('.rolelist').click(function () {
            jQuery("#register").show();
            jQuery("#reset").show();
            jQuery('.addrole').html('Add New role');
             jQuery('input[type="checkbox"]').removeAttr('disabled');
              jQuery('#rolename').removeAttr('disabled');
            jQuery('input:checkbox').attr('checked', false);
        });

        jQuery('#reset').click(function () {
            jQuery('input:checkbox').attr('checked', false);
        });
        $(document).on('click', '.editrole', function(event) {
             jQuery('#mask').show();
//        jQuery('.editrole').click(function () {
            jQuery('input[type="checkbox"]').removeAttr('disabled');
             jQuery("#register").show();
            jQuery("#reset").show();
            jQuery('.addrole').html('Edit role');
            var id = jQuery(this).attr("id");
            jQuery("#register").attr("value", "update");
            var dataString = '&edit_role=' + id;
            jQuery.ajax({
                type: "POST",
                url: '<?= $this->url(array('controller' => 'auth', 'action' => 'roles')) ?>',
                data: dataString,
                success: function (j) {

                    var json = jQuery.parseJSON(j);

                    jQuery('#rolename').val(json.d);
                    jQuery('#role_id').val(json.e);
                    jQuery(json.a).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery('.' + k).attr('checked', true);
                        });
                    });

                    jQuery(json.b).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery(v).each(function (i1, val1) {
                                jQuery.each(val1, function (a, b) {

                                    jQuery('.' + k + a).attr('checked', true);
                                });
                            });
                        });
                    });

                    jQuery(json.c).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery(v).each(function (i2, val2) {

                                jQuery.each(val2, function (c, d) {

                                    jQuery('.' + k + c).attr('checked', true);
                                });
                            });
                        });
                    });
  jQuery('#myTab a[href="#addrole"]').tab('show');
   jQuery('#mask').hide();
                }
            });
        });
        
        
         $(document).on('click', '.viewrole', function(event) {
//         jQuery('.viewrole').click(function () {
 jQuery('#mask').show();
         
         jQuery('input[type="checkbox"]').attr('disabled','true');
          jQuery('#rolename').attr('disabled','true');
            jQuery('.addrole').html('View role');
            var id = jQuery(this).attr("id");
            jQuery("#register").hide();
            jQuery("#reset").hide();
            var dataString = '&edit_role=' + id;
            jQuery.ajax({
                type: "POST",
                url: '<?= $this->url(array('controller' => 'auth', 'action' => 'roles')) ?>',
                data: dataString,
                success: function (j) {

                    var json = jQuery.parseJSON(j);

                    jQuery('#rolename').val(json.d);
                    jQuery('#role_id').val(json.e);
                    jQuery(json.a).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery('.' + k).attr('checked', true);
                        });
                    });

                    jQuery(json.b).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery(v).each(function (i1, val1) {
                                jQuery.each(val1, function (a, b) {

                                    jQuery('.' + k + a).attr('checked', true);
                                });
                            });
                        });
                    });

                    jQuery(json.c).each(function (i, val) {
                        jQuery.each(val, function (k, v) {

                            jQuery(v).each(function (i2, val2) {

                                jQuery.each(val2, function (c, d) {

                                    jQuery('.' + k + c).attr('checked', true);
                                });
                            });
                        });
                    });
  jQuery('#myTab a[href="#addrole"]').tab('show');
   jQuery('#mask').hide();
                }
            });
        });

  $(document).on('click', '.delete', function(event) {
//jQuery('.delete').click(function () {
     if(confirm("Are you sure you want to delete this?")){
     }
    else{
        return false;
    }
});

        jQuery('input[type=checkbox]').live('click', function () {

            if (jQuery(this).attr('checked'))
            {

                var check = jQuery(this).attr('check');

                jQuery('.' + check + 'module_check').attr('checked', true);
                jQuery('.' + check + 'module_check_view').attr('checked', true);
            }
            else {
                var check = jQuery(this).attr('check');
                jQuery('.' + check + 'module_check').attr('checked', false);
                jQuery('.' + check + 'module_check_view').attr('checked', false);

            }
        });


        jQuery('input[type=checkbox]').live('click', function () {
            var role = jQuery(this).attr('role');
            if (role) {
                var numberOfChecked = jQuery('.' + role + 'roles:checked').length;
                if (numberOfChecked == 0) {
                    jQuery('.' + role + 'role').attr('checked', false);
                }
//             if(numberOfChecked>=1){jQuery('.'+role+'role').attr('checked', true);}
            }

        });

        jQuery('input[type=checkbox]').live('click', function () {

            var module = jQuery(this).attr('module');

            var check = jQuery(this).attr('resource');



            if (jQuery(this).attr('checked'))
            {
                var check = jQuery(this).attr('resource');
                var res = jQuery(this).attr('resourceId');
                jQuery('.module' + check).attr('checked', true);
                jQuery('.' + res + 'resource_check_view').attr('checked', true);
            }
            else {
                var check = jQuery(this).attr('resource');
                var res = jQuery(this).attr('resourceId');

                jQuery('.' + res + 'resource_check_view').attr('checked', false);
                jQuery('.' + res + 'resource_check_create').attr('checked', false);
                jQuery('.' + res + 'resource_check_edit').attr('checked', false);
                jQuery('.' + res + 'resource_check_approve').attr('checked', false);

                var numberOfChecked = jQuery('.' + module + ':checked').length;
                if (numberOfChecked == 0)
                {
                    jQuery('.module' + check).attr('checked', false);
                }

            }
        });
        
        
        $(document).on("click", "tbody tr td .imgswap", function() {
        var id = $(this).attr("id");
        var so_id = id.split("_");
      
        if ($(this).attr("class") == "imgswap") {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
            this.src = this.src.replace("_off", "_on");
            var status = '1';
        } else {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
            this.src = this.src.replace("_on", "_off");
            var status = '0';
        }
        $(this).toggleClass("on");

        var dataString = '&type=changestatus&id=' + so_id[1] + '&status=' + status;

        $.ajax({
            type: "POST",
            url: '<?=$this->url(array('controller'=>'auth','action'=>'changerolestatus'))?>',
            data: dataString,
            success: function(j) {
      
                
            }
        });
    });


    });
    
</script>
    
<?php echo $this->render('navebar/leftnavbar.phtml'); ?>
<div class="span9" id="content">
    <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>


    <!--DELETE BOOK-->
    <div id="accordion">

        <div class="row-fluid">
            <div class="span12">
                <!-- block -->
                <div class="block">
                    <div class="navbar navbar-inner block-header">
                        <div class="muted pull-left">Role Management</div>
                        
                    </div>
                    
                    <div class="block-content collapse in">
                        <?php if($this->permission['view']==1){ ?>
                        <ul class="nav nav-tabs" id="myTab">
  
  <li class="active"><a class="rolelist" href="#viewrole">Role List</a></li>
  <?php if(($this->permission['create']==1)||($this->permission['edit']==1)){ ?>
  <li><a href="#addrole" class="addrole">Add New Role</a></li>
  <?php } ?>
  
 
</ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="viewrole">
                                
                 <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th style="width:50px;">SI No</th>
                                                <th>Role Name</th>
                                                <th>Action</th>
                                                <th>Status</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $rol=$this->roledel; $i=1; foreach($this->roleList as $roles){ ?>
                                            <tr><td><?=$i++;?></td>
                                                <td><?=$roles['acl_role_name']?></td>
                                                
                                                
                                                <td style='width:200px;'>
                                                    <?php if (in_array($roles['acl_role_id'], $rol)) { 
}else{?>
                                                    <a class='delete' href="<?php echo $this->baseUrl(); ?>/admin/auth/roles/delete_role/<?=$roles['acl_role_id']?>" >
<?php echo 'DEL /'; ?></a><?php }?>
                                                    <?php if(($this->permission['edit']==1)){ ?>
                                                    <a href="#" class="editrole" id="<?=$roles['acl_role_id']?>">
                                                <?php echo ' EDIT'; ?></a>
                                                    
                                                    <a href="#" class="viewrole" id="<?=$roles['acl_role_id']?>">
                                                <?php echo '/ VIEW'; ?></a>
                                                    <?php }?>
                                                </td> 
                                                <td>
                                                    <?php if($roles['status'] == '0'){ ?>
                                                    <a   style="cursor:pointer;">
                                                    <img class="imgswap" id="approval_<?php echo $roles['acl_role_id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    </a>
                                                    <?php }  if($roles['status'] == '1'){ ?>
                                        <a   style="cursor:pointer;">
                                                    <img class="imgswap on" id="approval_<?php echo $roles['acl_role_id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                        </a>
                                                <?php } ?>
                                                </td>
                                                
                                            </tr>
                                            <?php }?>
                                           
                                            
                                        </tbody>
                                    </table>               
                            </div>
                            <div class="tab-pane " id="addrole">
                                
                                <form action="<?= $this->url(array('controller' => 'auth', 'action' => 'roles')) ?>" method="post" onsubmit="return CheckForm(this)" name="role-form" id="role-form">
 <input type="hidden" name="role_id" id="role_id" class="role_id" value="" >
 <div class="formvalue">
              <div class="form-left pull-left">
 <label for="role name" class="required">Role name</label>              </div>
              <div class="form-right pull-left">
                            <input type="text" value="" placeholder="Enter role name" onkeypress="return isAlpha(event)" name='rolename' id='rolename' class="required-entry validate-alpha input-text form-control" required='true'>
              </div>
          </div>
                           
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    
                                    <tr>
                                        <th>Functions</th>
                                        <th>view</th>
                                        <th>create</th>
                                        <th>edit</th>
                                        <th>approve</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    <?php
                                    $modules = $this->module;
                                    $resource = $this->resource;
                                    ?>
                                    <?php foreach ($modules as $_modules): ?>
                                        <tr>
                                            <td colspan="5">
                                                <input class="form-control <?= $_modules['acl_module_id']; ?> module<?= $_modules['acl_module_id']; ?>" type="checkbox" check="<?= $_modules['acl_module_id']; ?>" module="<?= $_modules['module_id']; ?>" name="module<?= $_modules['acl_module_id']; ?>" value="<?= $_modules['module_id']; ?>" id="module<?= $_modules['module_id']; ?>" />
                                                <a hidefocus="on" href="#" id="">
                                                    <span style="font-weight:bold;">
                                                        <?= $_modules['module_name']; ?>
                                                    </span>
                                                </a>

                                            </td>

                                        </tr>

                                        <?php foreach ($resource[$_modules['module_id']] as $_resource): ?>
                                            <tr>
                                                <td >
                                                    <input module="<?= $_modules['module_id']; ?>" class="<?=$_resource['acl_controller_id'].'role'; ?> <?= $_modules['module_id']; ?> <?=$_modules['acl_module_id'].'module_check' ?> form-control <?=$_modules['module_id']. $_resource['acl_controller_id']; ?>" roles="<?=$_resource['acl_controller_id']; ?>" resource="<?=$_modules['acl_module_id']; ?>" resourceId="<?=$_resource['acl_controller_id']; ?>" type="checkbox" name="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>" value="<?= $_resource['acl_controller_id']; ?>" id="resource<?= $_resource['acl_controller_id']; ?>" style="
                                                          <?php if(($_resource['acl_controller_id']=='4')||
                                                                  ($_resource['acl_controller_id']=='12')||
                                                                  ($_resource['acl_controller_id']=='13')||
                                                                  ($_resource['acl_controller_id']=='15')||
                                                                  ($_resource['acl_controller_id']=='16')||
                                                                  ($_resource['acl_controller_id']=='17')){?> margin-left: 30px;<?php } else{ ?>margin-left:60px;<?php } ?>
                                                           " >
                                                    <a hidefocus="on" href="#" id="">
                                                        <span style="<?php if(($_resource['acl_controller_id']=='4')||
                                                                  ($_resource['acl_controller_id']=='12')||
                                                                  ($_resource['acl_controller_id']=='13')||
                                                                  ($_resource['acl_controller_id']=='15') ||
                                                                  ($_resource['acl_controller_id']=='16')||
                                                                  ($_resource['acl_controller_id']=='17')){?> font-weight:bold;<?php }?>"><?= $_resource['controller_name']; ?> </span>
                                                     
                                                    </a>
                                                </td>
                                                <td><?php if($_resource['view']=='1'){ ?>  <input module="<?= $_modules['module_id']; ?>"  type="checkbox" name="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_view" value='1' id="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_view" role="<?=$_resource['acl_controller_id']; ?>" class="permission_role <?=$_resource['acl_controller_id'].'roles'; ?> <?=$_resource['acl_controller_id'].'role_view'; ?> <?= $_modules['module_id']; ?> <?=$_resource['acl_controller_id']; ?>view <?=$_modules['acl_module_id'].'module_check_view' ?>  <?=$_resource['acl_controller_id'].'resource_check_view' ?>" ><?php }?></td>
                                                <td><?php if($_resource['create']=='1'){ ?> <input module="<?= $_modules['module_id']; ?>"  type="checkbox" name="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_create" value='1' id="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_create" role="<?=$_resource['acl_controller_id']; ?>" class="permission_role <?=$_resource['acl_controller_id'].'roles'; ?> <?= $_modules['module_id']; ?> <?= $_resource['acl_controller_id']; ?>create <?=$_resource['acl_controller_id'].'resource_check_create' ?>" ><?php }?></td>
                                                <td> <?php if($_resource['edit']=='1'){ ?> <input module="<?= $_modules['module_id']; ?>"  type="checkbox" name="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_edit" value='1' id="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_edit" role="<?=$_resource['acl_controller_id']; ?>" class="permission_role <?=$_resource['acl_controller_id'].'roles'; ?> <?= $_modules['module_id']; ?> <?= $_resource['acl_controller_id']; ?>edit <?=$_resource['acl_controller_id'].'resource_check_edit' ?>"><?php }?></td>
                                                <td> <?php if($_resource['approve']=='1'){ ?><input module="<?= $_modules['module_id']; ?>" type="checkbox" name="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_approve" value='1' id="<?= $_modules['module_id'] . $_resource['acl_controller_id']; ?>_approve" role="<?=$_resource['acl_controller_id']; ?>" class="permission_role <?=$_resource['acl_controller_id'].'roles'; ?> <?= $_modules['module_id']; ?> <?= $_resource['acl_controller_id']; ?>approve <?=$_resource['acl_controller_id'].'resource_check_approve' ?>" ><?php }?></td>
                                            </tr>
                                        <?php endforeach; ?>



                                    <?php endforeach; ?>


                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td> <input type="submit" name="register" id="register" value="Create Role" class="btn btn-primary" ></td>
                                        <td><input type="reset" name="reset" value="Reset" id="reset" class="btn btn-primary reset"></td>
                                    </tr>     


                                </tfoot>
                            </table>
                        </form> 
                            </div>
                        </div>
                         <?php } else  { echo 'You are not authorized person to access this module'; } ?>
                    </div>
                   
                </div>
            </div>
            <!-- /block -->
        </div>

    </div>
    <!--END-->






</div>
</div>


               
<style>
    ul{list-style: none;}
    tfoot tr,tfoot td{border-bottom: none !important;
                      border-left: none !important;
                      border-right: none !important;}
    input[type="radio"], input[type="checkbox"]{margin-top: 0px !important;}

</style>


