<div class="span9" id="content">
    <div class="row-fluid">
                        
                        	<div class="navbar">
                            	<div class="navbar-inner">
	                                <ul class="breadcrumb">
	                                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                                    <li>
	                                        <a href="#">Dashboard</a> <span class="divider">/</span>	
	                                    </li>
	                                    <li>
	                                        <a href="#">Chat Users</a> <span class="divider">/</span>	
	                                    </li>
<!--	                                    <li class="active">Tools</li>-->
	                                </ul>
                            	</div>
                        	</div>
                    	</div>
    
                    <div class="row-fluid">
                        <div class="span12">
                        <!-- block -->
                        <div class="block">
                            <div class="navbar navbar-inner block-header">
                                <div class="muted pull-left">Users</div> </div>
                                <!--<div class="pull-right"><span class="badge badge-warning">View More</span>-->
                               <div class="block-content collapse in">
                                   
                                   <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>User Name</th>
                                                
                                                <th>Available</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach($this->users as $user):?>
                                            <tr><td><?php echo $i+1;;
                                            $i++;?></td>
                                                <td><a href="javascript:void(0)" onclick="javascript:chatAdmin('<?=$user['from_user']?>','','admin','reply')">Chat With <?=$user['from_user']?></a></td> 
                                                <td>Online/offline</td>
                                                
                                                
                                                
                                            
                                          
                                            </tr><?php endforeach; ?>
                                            
                                        </tbody>
                                    </table>
                                  
                            </div>
                       
                        </div>
                        <!-- /block -->
                        
                      
                    </div>
                </div>
</div>  


