<!DOCTYPE html>
<html class="has-fixed-nav">
  <head>
<!--  	<meta charset="utf-8">-->
    <meta http-equiv="Content-type" content="application/epub+zip;text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <?php echo $this->headTitle(); ?>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css">

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/font-awesome.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/animate.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/flexslider.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/chat/chat.css">
    
    
    <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/chat/chat.js"></script>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/public/clematix/images/favicon.ico">

    <!-- Color Scheme -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/colors/purple.css">
  
  
  <!-- JS Libraries -->

  
 <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/flexslider.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.backstretch.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.nav.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.appear.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.countTo.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.mixitup.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/owl.carousel.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/jquery.validation.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/respond.js"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/parallax-bg.js"></script>  
  <!-- Main.js File -->  
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/main.js"></script>
  



  
	
</head>

<body>
  <!-- Preloader -->
  <div id="mask">
    <div id="loader">      
    </div>
  </div>
            <!--header-->
<?php echo $this->render('header.phtml');  ?> 

            <!--main-->
<?php echo $this->layout()->content ?>
 
            <!--footer-->
<?php echo $this->render('footer.phtml') ?> 

 



</body>
</html>

