 
 <style type="text/css">
    .bs-example{
    	margin: 20px;
    }
  .accordion-toggle {cursor: pointer;}
  .accordion-content {display: none;}
  .accordion-content.default {display: block;}
  .accordion-content{padding:10px; border-bottom:1px solid #ccc;}
  .accordion h4{
	background-color:#f9f9f9;
	padding:10px; 
	font-size:16px;
	border-bottom:1px solid #ccc; 
  }
  a, a:hover, a:focus{
outline:0;	
}
#accordion{
border:1px solid #ccc;
margin:0;
border-bottom:0;	
}
.accordion h4{
margin:0;	
}
#ininvetry span{margin:20px;font-weight: bold;font-size:14px;}
#ininvetry span input{margin-right:10px;}
</style>
   
  
<div class="span1" ></div>
     
<div class="span10" id="content">
    
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Status</div>
                                   
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#workorderlist">WO List</a></li>

  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="workorderlist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th style="width:40px;">SI No</th>
                                                <th>WO #</th>
                                                 <th>SO #</th>
                                                <th>Part no</th>
                                                <th>Project</th>
                                                 <th>WO date</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                           <?php $i=1; foreach($this->wo as $wo){?>
                                            <tr>
                                                <td><?=$i++;?></td>
                                                <td><?=$wo['wono']?></td>
                                                 <td><?=$wo['so']?></td>
                                                 <td><?=$wo['partno']?></td>
                                                 <td><?=$wo['project']?></td>
                                                 <td><?=$wo['date']?></td>
                                              
                                                <td>
                                                       <?php if($wo['status']=='0'){?>
                                                <a  class="viewwo" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo ' OPEN'; ?></a>
                                                       <?php } else{?>
                <a  class="viewwo" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo ' CLOSE'; ?></a>
                                                       <?php }?>

                                                </td>
                                                
                                            </tr>
                                           <?php }?>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  
    </div>
 

                                     
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   

 <script type="text/javascript">
  $(document).ready(function($) {
    $('#accordion').find('.accordion-toggle').click(function(){

      //Expand or collapse this panel
      $(this).next().slideToggle('fast');

      //Hide the other panels
//      $(".accordion-content").not($(this).next()).slideUp('fast');

    });
  });
</script>
     
    

</div>




