<style type="text/css">
    .bs-example{
    	margin: 20px;
    }
  .accordion-toggle {cursor: pointer;}
  .accordion-content {display: none;}
  .accordion-content.default {display: block;}
  .accordion-content{padding:10px; border-bottom:1px solid #ccc;}
  .accordion h4{
	background-color:#f9f9f9;
	padding:10px; 
	font-size:16px;
	border-bottom:1px solid #ccc; 
    }
  a, a:hover, a:focus{
outline:0;	
}
#accordion{
border:1px solid #ccc;
margin:0;
border-bottom:0;	
}
.accordion h4{
margin:0;	
}
</style>
   
   <script type="text/javascript">
     
     
   $(document).ready(function(){
       
         function okcalc(id){
               var rcvd = $('#rcvdqty_'+id).val();
               var okqty = $('#okqty_'+id).val();
               
               var rejected = parseInt(rcvd) - parseInt(okqty);
               $('#rejectedqty_'+id).val(rejected);
               if(parseInt(okqty) > parseInt(rcvd)){
                  $('#okqty_'+id).focus();
                  alert("Accepted Qty is greater than Received");
                  return false;
              }
              else{
                  return true;
              }
              
          }
          
          
        function rcvdcalc(id){
               var poqty = $('#poqty_'+id).val();
               var rcvd = $('#rcvdqty_'+id).val();
//               alert(poqty);
//               alert(rcvd);
              if(parseInt(rcvd) > parseInt(poqty)){
                  $('#rcvdqty_'+id).focus();
                  alert("Received Qty is greater than PO Qty");
                  return false;
              }
              else{
                  return true;
              }
          }
          
          
       $(document).on("click", ".addstatus", function(){
            $('#grnform')[0].reset();
       });
       
            $(document).on("click", ".editgrn", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
           var dataString ='&type=getvendor&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'getgrn'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                               //alert(k+'-'+v);
                               if(k=='vend_po'){
                                     $.each(v,function(k1,v1){
                                                $("select#vendor_po").append("<option value="+k1+">"+v1+"</option>");
                                        });
                                    }
                                if(k=='materials'){
                                     
                                        var k1;
                                        $(v).each(function(i,val){
                          
                                        var k1= ++i;
                                       $('#itemrows').append("<tr>\n\
                                                    <td style='width:20px;' id='slno_"+k1+"'>"+k1+"\
                                                        <input type='hidden' id='grn_mat_id_"+k1+"' name='grn_mat_id[]' value='"+val.id+"'/></td>\n\
                                                    <td><span id='item"+k1+"'>"+val.part_no+"</span><input type='hidden' name=item[] id='item_"+k1+"' value='"+val.item+"'/></td>\n\
                                                    <td><span id='desc_"+k1+"'>"+val.desc+"</span><input type='hidden' id='descrip_"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' name='poqty[]' id='poqty_"+k1+"' type='text' value='"+val.poqty+"' required style='width:80px;' onkeypress='return isNumber(event)' readonly></td>\n\
                                                    <td><input style='width:40px;' name='rcvdqty[]' id='rcvdqty_"+k1+"' type='number' value='' max='"+val.poqty+"' value='"+val.rcvdqty+"' required style='width:80px;' min='0' onkeypress='return isNumber(event)' readonly class='received_qty'></td>\n\
                                                    <td>    <input type='hidden' id='ok_"+k1+"' value='"+val.okqty+"'/>\n\
                                                            <input style='width:40px;' name='okqty[]' id='okqty_"+k1+"' type='number' value='"+val.okqty+"' required style='width:80px;' onkeypress='return isNumber(event)' min='0' class='accepted_qty'></td>\n\
                                                    <td><input name='rejectedqty[]' id='rejectedqty_"+k1+"' type='text' value='"+val.rejectedqty+"' style='width:80px;' onkeypress='return isNumber(event)' readonly></td>\n\
                                                    <td><span id='uom_"+k1+"'>"+val.uom+"</span><input type='hidden' id='uom"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' type='text' name='ast_sl[]' id='ast_sl_"+k1+"' value='"+val.ast_sl+"' onkeypress='return isNumber(event)'></td>\n\
                                                    <td><input style='width:75px;' type='text' name='mfgdate[]' id='mfgdate_"+k1+"' value='"+val.mfgdate+"' class='mfgdate' readonly></td>\n\
                                                    <td><input style='width:75px;' type='text' name='expiry[]' id='expiry_"+k1+"' value='"+val.expiry+"' class='expirydate' readonly></td>\n\
                                                    <td>    <input type='hidden' name='toadd[]' id='toadd_"+k1+"' value=''/><input type='hidden' name='todel[]' id='todel_"+k1+"' value=''/>\n\
                                                            <input type='hidden' id='uniquesl_"+k1+"' value='"+val.serial+"'/>\n\
                                                            <textarea name='serial[]' id='serial_"+k1+"' rows='3' cols='5' readonly>"+val.serial+"</textarea><img src='<?php echo $this->baseUrl();?>/public/images/generate-icon.png' id='slimg_"+k1+"' class='serialgen_edit generate_sl_icon' /></td></tr>");
    
                                });
                                }
                              $('#'+k).val(v);     
                    });
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
    
       $(document).on("click", ".viewgrn", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
              //  alert(id)
           var dataString ='&type=getgrn&id='+id;
            //alert(dataString);
            $('#save_button').addClass("hidden");
            $('#button_div').addClass("span9").removeClass("span7");
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'getgrn'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              if(k=='vend_po'){
                                     $.each(v,function(k1,v1){
                                                $("select#vendor_po").append("<option value="+k1+">"+v1+"</option>");
                                        });
                                    }
                                if(k=='materials'){
                                        var k1;
                                        $(v).each(function(i,val){
                          
                                        var k1= ++i;
                                       $('#itemrows').append("<tr>\n\
                                                    <td style='width:20px;' id='slno_"+k1+"'>"+k1+"</td>\n\
                                                    <td><span id='item"+k1+"'>"+val.part_no+"</span><input type='hidden' name=item[] id='item_"+k1+"' value='"+val.item+"'/></td>\n\
                                                    <td><span id='desc_"+k1+"'>"+val.desc+"</span><input type='hidden' id='descrip_"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' name='poqty[]' id='poqty_"+k1+"' type='text' value='"+val.poqty+"' required style='width:80px;' onkeypress='return isNumber(event)' disabled></td>\n\
                                                    <td><input style='width:40px;' name='rcvdqty[]' id='rcvdqty_"+k1+"' type='text' value='"+val.rcvdqty+"' required style='width:80px;' onkeypress='return isNumber(event)' disabled ></td>\n\
                                                    <td><input style='width:40px;' name='okqty[]' id='okqty_"+k1+"' type='text' value='"+val.okqty+"' required style='width:80px;' onkeypress='return isNumber(event)' disabled></td>\n\
                                                    <td><input name='rejectedqty[]' id='rejectedqty_"+k1+"' type='text' value='"+val.rejectedqty+"' required style='width:80px;' onkeypress='return isNumber(event)' disabled></td>\n\
                                                    <td><span id='uom_"+k1+"'>"+val.uom+"</span><input type='hidden' id='uom"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' type='text' name='ast_sl[]' id='ast_sl_"+k1+"' value='"+val.ast_sl+"' onkeypress='return isNumber(event)' disabled></td>\n\
                                                    <td><input style='width:75px;' type='text' name='mfgdate[]' id='mfgdate_"+k1+"' value='"+val.mfgdate+"' disabled></td>\n\
                                                    <td><input style='width:75px;' type='text' name='expiry[]' id='expiry_"+k1+"' value='"+val.expiry+"' disabled></td>\n\
                                                    <td><textarea name='serial[]' id='serial_"+k1+"' rows='3' cols='5' readonly>"+val.serial+"</textarea></td></tr>");
    
                                });
                                }
                              $('#'+k).val(v);  
                              $('#'+k).attr("disabled",true); 
                           
                               });
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
         $(document).on("click", ".imgswap", function(){
         var id = $(this).attr("id");
         var vendor_id = id.split("_"); 
         $('#mask').show();
            if ($(this).attr("class") == "imgswap") {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
                this.src = this.src.replace("_off", "_on");
                var status = '1';
            } else {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
                this.src = this.src.replace("_on", "_off");
                var status = '0';
            }
            $(this).toggleClass("on");
            
             var dataString ='&type=approvegrn&vendorid='+vendor_id[1]+'&status='+status;
            //alert(dataString)
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'approvegrn'))?>',
                        data: dataString,
                success: function(j) {
                     window.location.replace("<?=$this->url(array('controller'=>'grn','action'=>'index'))?>");
                    $('#mask').hide();
                }
            });
           
            
        });
        
        $('.vendor_name').change(function(){
              var val = $(this).attr("value");
              $("select#vendor_po").html("");
              $("select#vendor_po").append("<option value=''>Select</option>");
             var dataString ='&type=getvendorpos&val='+val;
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'getvendorpos'))?>',
                data: dataString,
                success: function(j) {
                    var k1;
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                         // alert(val.vendor_po);
                                    $("select#vendor_po").append("<option value="+val.id+">AAPL/PO/"+val.vendor_po+"</option>");
                       
                     });
                    //$('div#addstatus').html(result);
                    }
                });
               // partNoFormat();
            });
            
             $('.vendor_po').change(function(){
              var val = $(this).attr("value"); 
              $('#itemrows').html('');
              $('#mask').show();
              var dataString ='&type=getvendorpo_materials&val='+val;
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'getvendorpomaterials'))?>',
                data: dataString,
                success: function(j) {
                    var k1;
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                          
                           var k1= ++i;
                                       $('#itemrows').append("<tr>\n\
                                                    <td style='width:20px;' id='slno_"+k1+"'>"+k1+"</td>\n\
                                                    <td><span id='item"+k1+"'>"+val.part_no+"</span><input type='hidden' name=item[] id='item_"+k1+"' value='"+val.item+"'/></td>\n\
                                                    <td><span id='desc_"+k1+"'>"+val.desc+"</span><input type='hidden' id='descrip_"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' name='poqty[]' id='poqty_"+k1+"' type='text' value='"+val.pending+"' required style='width:80px;' onkeypress='return isNumber(event)' readonly></td>\n\
                                                    <td><input style='width:60px;' name='rcvdqty[]' id='rcvdqty_"+k1+"' type='number' value='' max='"+val.pending+"' required style='width:80px;' min='0' onkeypress='return isNumber(event)' class='received_qty'></td>\n\
                                                    <td><input style='width:60px;' name='okqty[]' id='okqty_"+k1+"' type='number' value='' required style='width:80px;' min='0' onkeypress='return isNumber(event)' class='accepted_qty'></td>\n\
                                                    <td><input name='rejectedqty[]' id='rejectedqty_"+k1+"' type='text' value='' style='width:80px;' onkeypress='return isNumber(event)' readonly></td>\n\
                                                    <td><span id='uom_"+k1+"'>"+val.uom+"</span><input type='hidden' id='uom"+k1+"' value=''/></td>\n\
                                                    <td><input style='width:40px;' type='text' name='ast_sl[]' id='ast_sl_"+k1+"' value='' onkeypress='return isNumber(event)'></td>\n\
                                                    <td><input style='width:75px;' type='text' name='mfgdate[]' id='mfgdate_"+k1+"' value='' class='mfgdate' readonly></td>\n\
                                                    <td><input style='width:75px;' type='text' name='expiry[]' id='expiry_"+k1+"' value='' class='expirydate' readonly></td>\n\
                                                    <td class='generate_sl_icon'><textarea name='serial[]' id='serial_"+k1+"' style='width:75%' rows='' cols='' readonly></textarea><img src='<?php echo $this->baseUrl();?>/public/images/generate-icon.png' id='slimg_"+k1+"' class='serialgen' /></td></tr>");
    
                     });
                    //$('div#addstatus').html(result);
                    $('#mask').hide();
                    }
                });
               // partNoFormat();
            });
            
             $(document).on("keyup", ".received_qty", function(){
                var id = $(this).attr("id");
                var id = id.split("_"); 
                var id = id[1];
                 var rcvd = $('#rcvdqty_'+id).val();
                 $('#okqty_'+id).attr("max",rcvd);
                 
              //  alert(id)
           // rcvdcalc(id);
            });
            
            $(document).on("keyup", ".accepted_qty", function(){
                var id = $(this).attr("id");
                var id = id.split("_"); 
                var id = id[1];
               okcalc(id);
            });
            
            $(document).on("click", ".serialgen", function(){
                var id = $(this).attr("id");
                var id = id.split("_"); 
                var id = id[1];
                var itemid = $('#item_'+id).val();
                var okqty = $('#okqty_'+id).val();
                if(okqty){
                var vendorid = $('.vendor_name').attr("value");
                //alert(vendorid);
//                alert(okqty);
                $('#mask').show();
                 var dataString ='&type=generateuniqueno&vendorid='+vendorid+'&itemid='+itemid+'&okqty='+okqty;
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'grn','action'=>'generateuniqueno'))?>',
                data: dataString,
                success: function(j) {
                        $('#serial_'+id).val(j);
                        $('#mask').hide();
                    //$('div#addstatus').html(result);
                    }
                });
                }
                else{
                alert('Please enter quantity for the material');
                }
            });
            
            $(document).on("click", ".serialgen_edit", function(){
                var id = $(this).attr("id");
                var id = id.split("_"); 
                var id = id[1];
                var itemid =    $('#item_'+id).val();
                var accepted =  $('#ok_'+id).val();
                var okqty =     $('#okqty_'+id).val();
                var vendorid =  $('.vendor_name').attr("value");
                var serial = $('#uniquesl_'+id).val();
                //alert(vendorid);
//                alert(okqty);
                var count = parseInt(okqty)-parseInt(accepted);
              //  alert(count)
                if(count < 0){
                    // To Del
                        alert('to del');
                        var remainsl = parseInt(accepted)-parseInt(okqty);
                     var sls = serial.split(",");
                  //   alert(sls.length);
                     var slslength = sls.length;
                    var count = slslength - remainsl;
                   // alert(count);
                    var showsl = '';
                    var delsl = '';
                    for(var i=0; i<count; i++){
                        showsl += sls[i]+',';
                    }
                   var showsl = showsl.slice(0,-1);
                    $('#serial_'+id).val(showsl);
                   // To del sl no 
                    for(var i=count+1; i<=slslength; i++){
                      delsl +=sls[i-1]+',';
                    }
                    var delsl = delsl.slice(0,-1);
                    $('#toadd_'+id).val('');
                    $('#todel_'+id).val(delsl);
                }
                else{
                    // To add
                 //   alert('to add');
                    var dataString ='&type=generateuniqueno&vendorid='+vendorid+'&itemid='+itemid+'&okqty='+count+'&serial='+serial;
                                        $.ajax({
                                            type: "POST",
                                            url: '<?=$this->url(array('controller'=>'grn','action'=>'generateuniquenoedit'))?>',
                                            data: dataString,
                                            success: function(j) {
                                                var json = $.parseJSON(j);
                                                $(json).each(function(i,val){
                                                  $.each(val,function(k,v){
                                                     if(k=='serial'){
                                                         $('#serial_'+id).val(v);
                                                    }
                                                    if(k=='toadd'){
                                                         $('#toadd_'+id).val(v);
                                                         $('#todel_'+id).val('');
                                                    }
                                                  });


                                                });

                                                //$('div#addstatus').html(result);
                                                }
                                            });
                }
               
            });
    
     });
 </script>
     
    
     
        
     <?php //echo $this->render('vendorlist.phtml');  ?> 

<div class="span12" id="content">
 
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">GRN</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#materiallist">GRN List</a></li>
  <li class="addstatus"><a href="#addstatus">Add New GRN</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="materiallist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable table-responsive" id="example">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Vendor Name</th>
                                                <th>Purchase Order</th>
                                                <th>GRN NO</th>
                                                <th>GRN Date</th>
                                                <th>Action</th>
                                                <!--<th>Approval</th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->grnlist as $value) { ?>
                                            <tr><td><?php echo $value[id] ?></td>
                                                <td><?php echo $value[vendor_name] ?></td>
                                                <td>AAPL/PO/<?php echo $value[vendor_po] ?></td>
                                                <td>AA/GRN/<?php echo $value[grn_no] ?></td>
                                                <td><?php echo $value[grn_date] ?></td>
                                                <td>
                                                    <a  class="viewgrn" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo ' VIEW'; ?></a>
<!--                                                    <?php if($value[status] == '0'){ ?><a  class="editgrn" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a><?php } ?>
                                                    <a href="<?php echo $this->baseUrl();?>/admin/vendor/deletevendor/delete/<?php echo $value[id]; ?>" class="book_delete" style="cursor:pointer;"><?php echo '/ DEL '; ?></a>-->
                                                    </td>
<!--                                                <td>
                                                    <?php if($value[status] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php }  if($value[status] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                <?php } ?>
                                                    </td>-->
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addstatus">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'grn','action'=>'savegrn'))?>" method="post" name="" id="grnform">
        <input type="hidden" name="id" id="id" value="" >
        
       
        
        <div class="clearfix"></div>
  <div class="bs-example">
  <div id="accordion">
  <h4 class="accordion-toggle">Vendor Information</h4>
  <div class="accordion-content default">

                 <div class="formvalue pull-left">
              <div class="form-left pull-left"><label for="part_no" class="required">Vendor Name:</label></div>
              <div class="form-right pull-left">
                   <select class="vendor_name" name="vendor_name" id="vendor_name" required="true">
                      <option value="">Select</option>
                      <?php   foreach ($this->vendorlist as $vendorlist) { ?>
                                <option  value="<?php echo $vendorlist[id] ?>"><?php echo $vendorlist[vendor_name] ?></option>
                       <?php } ?>
                  </select>
                  
              </div>
          </div>
        
        <div class="formvalue pull-left">
              <div class="form-left pull-left"><label for="vendor_po" class="required">Purchase Order:</label></div>
              <div class="form-right pull-left">
                  <select class="vendor_po" name="vendor_po" id="vendor_po" required="true">
                      <option value="">Select</option>
                  </select>
              </div>
          </div>
      
      <div class="formvalue pull-left">
                    <div class="form-left pull-left"><label for="grn_no" class="required">GRN #:</label></div>
                    <div class="form-right pull-left"><input type="text" name="grn_no" id="grn_no" value="<?php print_r($this->grnval); ?>" class="form-control" required="true" readonly></div>
                </div>
      
      <div class="formvalue pull-left">
                    <div class="form-left pull-left"><label for="date" class="required">GRN Date:</label></div>
                    <div class="form-right pull-left"><input type="text" name="grn_date" id="grn_date" value="" class="form-control" required="true" readonly></div>
                </div>
       
<div class="clearfix"></div>
  </div>
  <h4 class="accordion-toggle">Material Information</h4>
  <div class="accordion-content default table-responsive" style="width:95%;">

              <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable table-responsive" id="grntable">
                                        <thead>
                                            <tr>
                                                <th  rowspan='2'>SI No</th>
                                                <th  rowspan='2'>Part No</th>
                                                <th  rowspan='2'>Description</th>
                                                <th colspan="4">Quantity of Material</th>
                                                <th  rowspan='2'>UOM</th>
                                                <th  rowspan='2' style="width:50px;">Manufacturer Sl#/Batch#</th>
                                                <th  rowspan='2'>Mfg Date</th>
                                                <th  rowspan='2'>Expiry Date</th>
                                                <th  rowspan='2'>Asteria  Sl#/Batch #</th>
                                                
                                            </tr>
                                            <tr>
                                                <th>Ordered</th>
                                                <th>Received</th>
                                                <th>Accepted</th>
                                                <th>Rejected</th>
                                                
                                                
                                            </tr>
                                        </thead>
                                        <tbody id="itemrows">
                                          
                                        </tbody>
                                        
                                    </table>
<!--              <div style="float:right;">
      <div style="float:left; font-weight: bold; margin: 6px 10px;">Total: <span id="linetotal">0</span></div>
      <input type="hidden" name="total_amt" id="total_amt" value=""/>
       </div>-->
              
       
<div class="clearfix"></div>
  </div>
  
</div>
</div>

<div id="button_div" class="clearfix span7" style="float: right;" >
<div class="span2" id="save_button">
 <input class='btn btn-primary' type="submit" name="deptregister" id="deptregister" value="Save" class="btn btn-default" />
</div>
 
<div class="span1" id="back_button">
    <a href=""><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
</div>
      </div>

</form>
      
      </div>
  
  
</div>
 
<script>
  $(function () {
      $('#myTab a[href="#<?php echo $this->showid;?>"]').tab('show');
    $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
  })
</script>   
                                     
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   
<script type="text/javascript">
  $(document).ready(function($) {
    $('#accordion').find('.accordion-toggle').click(function(){

      //Expand or collapse this panel
      $(this).next().slideToggle('fast');

      //Hide the other panels
   //   $(".accordion-content").not($(this).next()).slideUp('fast');

    });
  });
</script>
 
</div>




