<style type="text/css">
    .bs-example{
    	margin: 20px;
    }
  .accordion-toggle {cursor: pointer;}
  .accordion-content {display: none;}
  .accordion-content.default {display: block;}
  .accordion-content{padding:10px; border-bottom:1px solid #ccc;}
  .accordion h4{
	background-color:#f9f9f9;
	padding:10px; 
	font-size:16px;
	border-bottom:1px solid #ccc; 
  }
  a, a:hover, a:focus{
outline:0;	
}
#accordion{
border:1px solid #ccc;
margin:0;
border-bottom:0;	
}
.accordion h4{
margin:0;	
}
.bom_detail{   
    width: 98%;
    height: 40px;
    border: 1px solid;
/*    background-color: #DDDDDD;*/
    margin-bottom: 10px;
    border-radius: 5px;
    padding: 5px;
}
.bom_detail p{margin: 0 auto;}

.form-addbom {
/*  max-width: 60%;
*/  padding: 19px 29px 29px;/*
  margin: 50px auto 20px;
  background-color: #fff;
  border: 1px solid #e5e5e5;*/
  -webkit-border-radius: 5px;
  -moz-border-radius: 5px;
  border-radius: 5px;
  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
  -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
  box-shadow: 0 1px 2px rgba(0,0,0,.05);
}
.form-left{width:45% !important;}
.form-right{width:50% !important;}
</style>


 <?php echo $this->render('navebar/leftnavbar.phtml'); 
?>

<div class="span9" id="content">
       <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Bill of Material</div>
                                    
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#materiallist">Bill of Material List</a></li>
  <li class="addstatus"><a href="#addbom">Add New Bill of Material</a></li>
  
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="materiallist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>BOM</th>
                                                <th>Part No</th>
                                                <th>Material Description</th>
                                                <th>Action</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  
  
    <div class="tab-pane" id="addbom">
  
        <div class='bom_detail'> </div>
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable  bom_material" id="example1">
                                        <thead>
                                            <tr>
                                                <th>BOM Id</th>
                                                <th>Part No</th>
                                                <th>Part description</th>
                                                <th>Quantity</th>
                                                <th>UOM</th>
                                                <th>Drawing no</th>
                                                <th>Drawing Rev no</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        
                                        <tbody role="alert" aria-live="polite" aria-relevant="all">
                                            
                                        </tbody>
                                    </table>
        <div class="row-fluid" id='add_new_bom' style='display: none;'> 
            <center>
          <center>Add New BOM</center>
          <br/>
       <div class="title">
           <form data-toggle="validator"  enctype="application/x-www-form-urlencoded" action="<?= $this->url(array('controller' => 'material', 'action' => 'bomadd')) ?>" method="post" id="form_addbom" name="form_addbom" class='form_addbom'>
               <input type="hidden" name="bom_id" id="bom_id" value="" class="inputDisabled">
               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="firstname" class="required">Part no:</label></div>
                   <div class="input-group form-right pull-left">

                       <select data-error=" " name="partno" id="partno" class="form-control" required="true">
                            <option value="">Select Part No</option>
                          
                           
                       </select>              
</div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>
               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Part description:</label></div>
                   <div class="form-right pull-left">
                       <input type="text" data-error=" " name="partdescription" value='' id="partdescription" class="form-control" required="true" readonly="true">
                                       </div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>
 


               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Uom:</label></div>
                   <div class="form-right pull-left">
                       <input type="text" data-error=" " name="uom_bom" value='' id="uom_bom" class="form-control" required="true" readonly="true">
                          
                   </div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>

               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Drawing No:</label></div>
                   <div class="form-right pull-left">
                      <input type="text" data-error=" " name="drawingno" value='' id="drawingno" class="form-control" required="true" readonly="true">
                           
                   </div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>

               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Drawing Rev No:</label></div>
                   <div class="form-right pull-left">
                       
                       <input type="text" data-error=" " name="drawing_revno"  value='' id="drawingno_revno" class="form-control" required="true" readonly="true">
                           
                   </div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>

               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Quanty:</label></div>
                   <div class="form-right pull-left">
                       <input type="number" data-error=" " name="quanty" pattern="^{1,}$" id="quanty" value="" class="form-control inputDisabled" required="true"></div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>
               <div class="formvalue form-group clearfix">
                   <div class="form-left pull-left"><label for="code" class="required">Description:</label></div>
                   <div class="form-right pull-left">
                       <textarea rows="5" cols="200" name="bom_description" id="bom_description" value="" class="form-control" required="true"></textarea>
                   </div>
                   <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
               </div>

               <div id="button_div" class="clearfix span7" style="float: right;" >
                   <div class="span2" id="save_button">
                       <a class='btn btn-primary'  name="save_bom" id="save_bom" value="Save" class="btn btn-default save_bom" />Save</a>
                   </div>

                   <div class="span1" id="back_button">
                       <a href=""><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
                   </div>
               </div>

           </form>
         

       </div> 
            </center>
       
       <script type="text/javascript">
      $(document).ready(function(){
          
        $('#partno').change(function(){
            var id= $(this).val();
             $.ajax({
                url: '<?=$this->url(array('controller'=>'material','action'=>'addbom'))?>',
                type: 'post',
                data:'&id=' + id,
                
                success: function(j) {
                     var json = $.parseJSON(j);
//                     console.log(json);
                     $('#partdescription').val(json.material_desc);
                     $('#uom_bom').val(json.uom);
                     $('#drawingno').val(json.drawing_no);
                     $('#drawingno_revno').val(json.revision_no);
                    }
                });
        });
          $('#save_bom').click(function(){
               var formdata = $('#form_addbom').serialize();
              $.post('<?php echo $this->url(array('controller'=>'material', 'action'=>'savebom')); ?>', { 'data': formdata })
               .done(function(data) {
                   console.log(data);
           if(data==0){alert('Already added in bom');}
           if(data==1){
               document.getElementById("form_addbom").reset();
                var bomid=$('#bom_id').val();
$.ajax({
                url: '<?=$this->url(array('controller'=>'material','action'=>'bom'))?>',
                type: 'post',
                data:'&bom_id=' + bomid,
                
                success: function(j) {
                      var json = $.parseJSON(j);
                      
                      var i=0;
//                  console.log(json.table);
                       $('#example1').dataTable().fnClearTable();
                       $(json.table).each(function(k,v){
//                       $.each(val,function(k,v){
                           var action='<a href="#" id="'+(i++)+'" class="view">VIEW /</a>\n\
                                      <a href="#" id="'+(i++)+'" class="view"> EDIT /</a>\n\
                                        <a href="#" id="'+(i++)+'" class="view"> DEL</a>';
                           $('#example1').dataTable().fnAddData( [v.bom_project_id,v.part_no,v.material_desc,v.quanty, v.uom, v.drawing_no,v.revision_no,action ] );
//                        });
                     });
                     $('.bom').removeClass('hidden');
                     $('#myTab a[href="#bom"]').tab('show');
                    }
                });
                $('#add_new_bom').hide();
                $('#addbom').show();
                $('#example1_wrapper').show();
            

           }
            
             });
        });
           

           $('.bom_add').click(function(){
                $('#example1_wrapper').show();
                $('#addbom').show();
                $('#add_new_bom').hide();
                
                var bomid=$(this).attr('id');
               $.ajax({
                url: '<?=$this->url(array('controller'=>'material','action'=>'bom'))?>',
                type: 'post',
                data:'&bom_id=' + bomid,
                
                success: function(j) {
                      var json = $.parseJSON(j);
                      console.log(json);
                      var bom_material='<p><span style="color:red;">PARN NO:</span> '+json.id.part_no+'</p><p><span style="color:red;">MATERIAL DESCRIPTION:</span>'+json.id.material_desc+'</p>';
                      $('.bom_detail').html(bom_material);
                      $('#bom_id').val(json.id.id);
                      var i=0;
                  
                      $('#example1').dataTable().fnClearTable();
                       $(json.table).each(function(k,v){
//                       $.each(val,function(k,v){
                           var action='<a href="#" id="'+v.id+'" class="view">VIEW /</a>\n\
                                      <a href="#" id="'+v.id+'" class="view"> EDIT /</a>\n\
                                        <a href="#" id="'+v.id+'" class="view"> DEL</a>';
                           $('#example1').dataTable().fnAddData( [v.bom_project_id,v.part_no,v.material_desc,v.quanty, v.uom, v.drawing_no,v.revision_no,action ] );
//                        });
                     });
                     $('.bom').removeClass('hidden');
                     $('#myTab a[href="#bom"]').tab('show');
                    }
                });
                
            });
            
            $('.addbom').click(function(){
            $(this).hide();
            $('#example1_wrapper').hide();
            $('#add_new_bom').show();
            });
        
    });
</script>
       
  </div> 
        <div style='float:right;'>
            <button id='addbom' value='' name='addbom' class='addbom btn btn-primary' >Add New</button>
        </div>
        
    </div>
 <script>
  $(function () {
      $('#myTab a[href="#<?php echo $this->showid;?>"]').tab('show');
    $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
  })
</script>   
    
   </div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   <script type="text/javascript">
  $(document).ready(function($) {
    $('#accordion').find('.accordion-toggle').click(function(){

      //Expand or collapse this panel
      $(this).next().slideToggle('fast');

      //Hide the other panels
      $(".accordion-content").not($(this).next()).slideUp('fast');

    });
  });
</script>

    

</div></div>




