<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/clematix/css/easy-responsive-tabs.css">
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/clematix/js/easyResponsiveTabs.js"></script>
<!-- Portfolio Section -->    
  <section id="portfolio" class="section">
    <div class="container">
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h1> <strong>Comment</strong> me créer ?</h1>
        <hr>
        <h2>Choisissez-moi parmi les configurations proposées</h2>
		<p>Si vous m’imaginez proche d’une de ces configurations alors sélectionnez-la.
		Au contraire, si vous avez votre propre idée de moi, alors décrivez-moi ou
		communiquez directement avec Clematixdigital, par <input type='hidden' value="<?php echo $this->baseUrl();?>/chat/chat/index" id='chat_post'/><a class='cchat' style="cursor:pointer;" title="">tchat</a> ou par <a href="#" title="">mail</a>; ils vous répondront très vite.
</p>
      </div>
      <!-- Portfolio Filters -->
      <ul id="filters">
          <li class="filter" data-filter="all">Tous</li>
          <li class="filter" data-filter="lorem">Lorem</li>
          <li class="filter" data-filter="ipsum">Ipsum</li>
          <li class="filter" data-filter="dolore">Dolore</li>
      </ul>
      <!-- End Portfolio Filters -->
    </div>
    <div class="portfolio-top"></div>
    
    <!--marketing description-->
    <a class='market' href="#market-descript"></a>
    <div style="display:none;">
            
        <div id="market-descript" style="clear:both; float:left;width:100%;height:50%;border:2px dotted #641e73;background-color: #eee;">
<div style="float:left; margin:30px 20px 10px 30px;">
<img src="<?php echo $this->baseUrl();?>/public/clematix/images/tick.png" />
</div>
<div style="margin:30px 20px 10px 180px;">
<h3 class="center up" style="color:#631d73;">Well done! </h3>

<br />
All your book components have now been uploaded. Once you place the order, we will prepare a first version of your enriched book which will be made available to you within 72 hours.

</div>

</div>
        
        
    </div>
    <!-- Portfolio Grid -->
    <ul id="portfolio-grid">
        
      <li class="mix lorem ipsum mix_all">
	  <div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/1.jpg" alt="0000">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Silk Light</span>
            <span>Photography </span>         
          </div>
		  
        </a>
      </li>
      <li class="mix ipsum mix_all">
		<div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/2.jpg" alt="1111">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Emma</span>
            <span>Photography / Video</span>
          </div>
        </a>
      </li>
      <li class="mix dolore mix_all">
		<div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/3.jpg" alt="">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Potrait</span>
            <span>Graphic</span>
          </div>
        </a>
      </li>
      <li class="mix dolore mix_all">
		<div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/4.jpg" alt="">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Shana</span>
            <span>Photography</span>
          </div>
        </a>
      </li>
      <li class="mix loreù mix_all">
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/5.jpg" alt="">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">The Model</span>
            <span>Photography</span>
          </div>
        </a>
      </li>
      <li class="mix ipsum mix_all">
		<div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/6.jpg" alt="">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Aleilde</span>
            <span>Graphic</span>
          </div>
        </a>
      </li>
      <li class="mix lorem mix_all">
		<div class="select"><a  class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/7.jpg" alt="">
        <a  class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Xo Bella</span>
            <span>Branding</span>
          </div>
        </a>
      </li>
      <li class="mix lorem mix_all">
		<div class="select"><a class="open-project btn-plein">Sélectionner</a></div>
        <img src="<?php echo $this->baseUrl();?>/public/clematix/images/portfolio/8.jpg" alt="">
        <a class="open-project">
          <div class="project-overlay">
            <i class="fa fa-plus-circle fa-3x"></i>
            <span class="project-name">Happy Pill</span>
            <span>Graphic</span>
          </div>
        </a>
      </li>
    </ul>
    <!-- End Portfolio Grid -->
    <!-- Ajax Loaded Portfolio -->
    <div id="project-extended">
      <div class="container">
        <ul id="project-controls">
          <li>
            <a href="#" id="close-project">
              <i class="fa fa-times fa-2x"></i>
            </a>
          </li>
        </ul>
        <div id="project-content"></div>
      </div>
    </div>
    <!-- End Ajax Loaded Portfolio -->
    <div class="portfolio-bottom"></div> 
  </section>
  <!-- End Portfolio Section -->
  
  <!-- personnalize Section -->    
  <section id="personnalize" class="section">
	<div class="container">
            
      <div class="title col-md-8 col-sm-10 col-xs-12">
		<h2> <strong>Personnalisez</strong> moi</h2>
                <hr>
		<p>Choisissez comment vous allez me personnaliser: <br />ajoutez-moi des vidéos, des bandes son, des images, des diapositives...</p>
		</div>
            
            
<form enctype="multipart/form-data" action="<?=$this->url(array('controller'=>'createbook','action'=>'index'));?>" method="POST" name="inputfiles" id="inputfiles">
			
            
            
        <div id="verticalTab">
            <ul class="resp-tabs-list">
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-text.png"> Text</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-Orientation.png"> Orientation</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-image.png"> Individual images</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-slideshow.png"> Slideshow</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-video.png"> Individual videos</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-audio.png"> Read aloud</li>
               
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-animation.png"> Animation effect</li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-questionnaire.png"> Multiple choice questionnaire <br><div style="padding-left:50px;text-transform:capitalize ">(set of questions and answers)</div></li>
                <li><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-cover.png"> Cover</li>
            </ul>
            <div class="resp-tabs-container">
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-text.png"> Text</div>
                    <p>
                   <div class="contentview">
                  <input name="single" type="radio" value="single"/> Single Page view <img style="padding-left:20px;" src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/singlepagebook.png">
                  <br><br>
                  <input name="double" type="radio" value="double"/> Double Page view <img style="padding-left:14px;" src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/doublepagebook.png">
                  
                   <br><br><br>
                   
                   Comments
                   
                   <textarea style="resize:none;"></textarea>
                   <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                  
                  </p>
                
                   </div>
                  
                  
                </div>
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-orientation.png"> Orientation</div>
                    <p>
                   <div class="contentview">
                  <input name="single" type="radio" value="single"/> portrait <img style="padding-left:20px;" src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/portrait.png">
                  <br><br>
                  <input name="single" type="radio" value="double"/> Landscape <img style="padding-left:14px;" src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/landscape.png">
                  
                  <br><br><br>
                   Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                  </div>
                  
                  </p>
                </div>
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-image.png"> Individual images</div>
                    <p>
                   
                   <div class="contentview">
                 Please Enter How many images do you upload? <br>
                 <div style="text-transform:capitalize; color:#515151;">(you can compress and upload .zip format)</div><br> <input name="" type="text" value=""/>   
                  <br><br><br><br>
                 Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                 
                  
                  </div>
                  
                  </p>
                </div>
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-slideshow.png"> Slideshow</div>
                    <p>
                  <div class="contentview">
                  <input name="single" type="radio" value="single"/> Page Full size 
                  <br><br>
                  <input name="single" type="radio" value="double"/> whatever size <br><input type="text" placeholder="width * height"> 
                   <div style="text-transform:capitalize; color:#515151;">(Ex: 500px * 300px)</div>
                     <br><br>
                     
                     <input type="checkbox"> automatic Slideshow
                      <br><br>
                      <input type="checkbox"> Slide transition effect
                  
                  <br><br><br>
                   Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                  </div>
                  
                  </p>
                </div>
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-video.png"> videos</div>
                    <p>
                  <div class="contentview">
                 Please Enter How many videos do you upload? <br>
                 <div style="text-transform:capitalize; color:#515151;">(you can compress and upload .zip format)</div><br> <input name="" type="text" value=""/>   
                  <br><br><br><br>
                 Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                 
                  
                  </div>
                  
                  </p>
                </div>
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-audio.png" > Read aloud</div>
                    <p>
                   
                   <div class="contentview">
                 <input type="radio" name="single"> Paragraph
                 <br><br>
                                  <input type="radio" name="single"> Sentence
                 <br><br>
                                  <input type="radio" name="single"> word
                 <br> <br> <br>
                 Choose Colour of read text <input type="color" name="single">
                 
                  <br><br><br><br>
                  
                 Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                 
                  
                  </div>
                  
                  </p>
                </div>
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-animation.png"> Animation Effect</div>
                    <p>
                  <div class="contentview">
               
                     <input type="checkbox"> text
                      <br><br>
                      <input type="checkbox"> image
                  
                  <br><br><br>
                   Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                  </div>
                  
                  </p>
                </div>
                
                
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-questionnaire.png"> Multiple choice questionnaire </div>
                    <p>
                  <div class="contentview">
               
                    
                  <br><br><br>
                   Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                  </div>
                  
                  </p>
                </div>
                
                
                
                
                <div>
                 <div class="tab-head"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/icons/icon-cover.png"> Cover</div>
                    <p>
                   
                   <div class="contentview">
                 <input type="radio" name="single"> sent by client
                 <br><br>
                                  <input type="radio" name="single"> designed by us
    <br><br><br><br>
                  
                 Comments
                   
                   <textarea style="resize:none;"></textarea>
                          <br><br>
                   
                   
                     Model Books
                  
                  <div class="modelbooks">
                   <ul>
                   <li>
                   
                   <a href="#"><img src="public/clematix/images/modeles/modelbook1.png"  /></a>
                   </li>
                   <li>
                     <a href="#"><img src="public/clematix/images/modeles/modelbook2.png" /></a>
                     </li>
                     <li>
                       <a href="#"><img src="public/clematix/images/modeles/modelbook3.png"  /></a>
                       </li>
                       </ul>
                  </div>
                 
                  
                  </div>
                  
                  </p>
                </div>
            </div>
        </div>    
            
            
            
            
            
            <div style="float:right; margin:10px 25px 10px 10px;">
           <h5> " All type of input files you can compress and upload .zip format " </h5>
            
            
            
            
            <input style="opacity:1; position:relative; display:inline;" type="file" id="publication" name="publication" value="Choose Your File" placeholder="Choose Your File" required="true"/>
            <input type="submit" value="Submit" name="submit" id="submit" class="btn-plein" style="float:right;" />
            
            
            <div id="progressbar" style="display:none;" >
                  <div id="progress" style="position:relative; width:400px; border: 1px solid #641e73; padding: 1px; border-radius: 3px;">
                 <div id="bar" style="background-color: #641e73; width:0%; height:20px; border-radius: 3px;"></div>
                  <div id="percent" style="position:absolute; display:inline-block; top:3px; left:38%;color:#EBB4BD;"></div >
                      </div>
<br/>
    
<div id="message"></div>
                   

      </div>
            
            </div>
	  </form>
            
            
		</div>
      
    
  </section>
  <!-- End personnalize Section -->
  
  <section id="commander"  class="section">
	<div class="container">
          <h2><strong>Commandez</strong> moi</h2>
          <hr>
		  <p>Well done! All your book components have now been uploaded. Once you place the order, we will prepare a first version of your enriched book which will be made available to you within 72 hours.<br />
			<br />You will be able to send us your comment and reach us using the appropriate form .<br />
			<!--<a href="#" title="" class="btn-plein">Add features</a><a href="#" title="" class="btn-plein">Place the order</a><a href="#" title="" class="btn-plein">réinitialiser</a>--></p>
	</div>
  </section>
  
  
  
<!--  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
-->  <script src="http://malsup.github.com/jquery.form.js"></script>
  
    <script>
$(document).ready(function()
{

	var options = { 
    beforeSend: function() 
    {$("#progressbar").show();
    	$("#progress").show();
    	//clear everything
    	$("#bar").width('0%');
    	$("#message").html("");
        $("#percent").html("0%");
    },
    uploadProgress: function(event, position, total, percentComplete) 
    {
    	$("#bar").width(percentComplete+'%');
    	$("#percent").html(percentComplete+'% complete');

    
    },
    success: function() 
    {
        $("#bar").width('100%');
    	$("#percent").html('uploded successfully');
$('.market').trigger('click'); 
    },
	complete: function(response) 
	{
		$("#message").html("<font color='#641e73'>"+response.responseText+"</font>");
	},
	error: function()
	{
		$("#message").html("<font color='red'> ERROR: unable to upload files</font>");

	}
     
}; 

     $("#inputfiles").ajaxForm(options);

});


$(".market").colorbox({inline:true, width:"60%",height:"50%"});
</script>