 <script type="text/javascript">
     
   $(document).ready(function(){
       
        
       $('.addproject').click(function(){
          $('#project_form')[0].reset();
           $('#save_button').removeClass("hidden");
           $('.inputDisabled').removeAttr("readonly");
            $('#button_div').addClass("span7").removeClass("span9");
       });
       
            $('.editproject').click(function(){
               $('#myTab a[href="#addproject"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
           var dataString ='&type=getpatient&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'getproject'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v);     
                    });
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
         
         $('.viewproject').click(function(){
               $('#myTab a[href="#addproject"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
             $('#save_button').addClass("hidden");
             $('#button_div').addClass("span9").removeClass("span7");
           var dataString ='&type=getproject&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'getproject'))?>',
                        data: dataString,
                success: function(j) {
                   //alert(j);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                             // alert(k); alert(v);
                                $('#'+k).val(v); 
                                $('#'+k).attr("readonly",true); 
                    });
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
         
         $(document).on("click", ".imgswap", function(){
         var id = $(this).attr("id");
         var vendor_id = id.split("_"); 
         
            if ($(this).attr("class") == "imgswap") {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
                this.src = this.src.replace("_off", "_on");
                var status = '1';
            } else {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
                this.src = this.src.replace("_on", "_off");
                var status = '0';
            }
            $(this).toggleClass("on");
            
             var dataString ='&type=changestatusproject&vendorid='+vendor_id[1]+'&status='+status;
           // alert(dataString)
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'changestatusproject'))?>',
                        data: dataString,
                success: function(j) {
                  //  alert(result);
                    //$('div#addstatus').html(result);
                }
            });
       });
          
     });
 </script>
     

<div class="span12" id="content">
     <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Project Master</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active projectlist"><a href="#projectlist">Project List</a></li>
  <li class="addproject"><a href="#addproject">Add New Project</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="projectlist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr> <th>#</th>
                                                <th>Project Name</th>
                                                <th>Project Code</th>
                                                <th>Action</th>
                                                <th>Status</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php $i=1;foreach ($this->project as $value) { ?>
                                            <tr>
                                                <td><?=$i++;?></td>
                                                <td><?php echo $value['project_name'] ?></td>
                                                <td><?php echo $value['project_code'] ?></td>
                                                <td>
                                                    <a  class="viewproject" id="<?php echo $value['project_id']; ?>" style="cursor:pointer;"><?php echo 'VIEW'; ?></a>
                                                    <a  class="editproject" id="<?php echo $value['project_id']; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a>
                                                    <!--<a href="<?php echo $this->baseUrl();?>/admin/material/projectmaster/delete_id/<?php echo $value['project_id']; ?>" class="book_delete" style="cursor:pointer;"><?php echo '/ DEL '; ?></a>-->
                                                    
                                                </td>
                                                <td>
                                                    <?php if($value[status] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php echo $value['project_id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php }  if($value[status] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php echo $value['project_id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                    <?php } ?>
                                                </td>
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addproject">
      <form enctype="application/x-www-form-urlencoded" action="<?= $this->url(array('controller' => 'material', 'action' => 'projectmaster')) ?>" method="post" id="project_form">
          <input type="hidden" name="project_id" id="project_id" value="" class="inputDisabled">
          <div class="formvalue form-group clearfix">
              <div class="form-left pull-left"><label for="firstname" class="required">Project Name:</label></div>
              <div class="input-group form-right pull-left">
                  <input type="text" name="name" id="project_name" value="<?php echo $this->data[name]; ?>" class="form-control inputDisabled" required="true">
              </div>
              <div class="form-left pull-left"></div>
          </div>
          <div class="formvalue form-group clearfix">
              <div class="form-left pull-left"><label for="code" class="required">Project Code:</label></div>
              <div class="form-right pull-left">
                  <input type="text" name="code" id="project_code" value="" class="form-control inputDisabled" disabled></div>
              <div class="form-left pull-left"></div><span class="help-block with-errors"></span>
          </div>

          <div id="button_div" class="clearfix span7" style="float: right;" >
              <div class="span2" id="save_button">
                  <input class='btn btn-primary' type="submit" name="project" id="project" value="Save" class="btn btn-default" />
              </div>

              <div class="span1" id="back_button">
                  <a href=""><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
              </div>
          </div>

      </form>
      
      </div>
  
  
</div>
   
                                     
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>


</div>




