 <script type="text/javascript">
     
   $(document).ready(function(){
       
       
        $(document).on("change", ".materialgroup", function(){
           var code = $(this).attr("value");
           $('#group_char').val(code)
        });
       
      
        $(document).on("click", ".addstatus", function(){
           $('#matgrp_form')[0].reset();
            $('#save_button').removeClass("hidden");
           $('.inputDisabled').removeAttr("readonly");
           $('#button_div').addClass("span7").removeClass("span9");
       });
       
          
             $(document).on("click", ".editgroup", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
              $('#mask').show();
               $('#save_button').removeClass("hidden");
             $('.contenttab').html("Edit Material Sub Category");
           var dataString ='&type=getgroup&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'getmaterialgroup'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              if(k == 'category'){
                                  if(v != 'M'){
                                      $('.mechfields').addClass("hidden");
                                  }
                                  else{
                                        $('.mechfields').removeClass("hidden");
                              }
                              }
                              
                              $('#'+k).val(v);     
                              if(k != 'group_desc'){
                                   $('#'+k).attr("readonly",true);  
                              }
                    });
                    });
                   $('#mask').hide();
                }
            });
         });
          $(document).on("click", ".listtab", function(){
            $('.contenttab').html("Add New Material Sub Category");
         });
         
          $(document).on("click", ".viewgroup", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
             $('#mask').show();
             $('.contenttab').html("View Material Sub Category");
           var dataString ='&type=getgroup&id='+id;
            // alert(dataString);
            $('#save_button').addClass("hidden");
            $('#button_div').addClass("span9").removeClass("span7");
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'getmaterialgroup'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
//                              alert(k);
//                              alert(v);
                              if(k == 'category'){
                                  if(v != 'M'){
                                      $('.mechfields').addClass("hidden");
                                  }
                                  else{
                                        $('.mechfields').removeClass("hidden");
                              }
                              }
                              $('#'+k).val(v);  
                                   $('#'+k).attr("readonly",true); 
                           
                               });
                               $('#mask').hide();
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
    
         
         $(document).on("click", ".imgswap", function(){
         var id = $(this).attr("id");
         var vendor_id = id.split("_"); 
         $('#mask').show();
            if ($(this).attr("class") == "imgswap") {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
                this.src = this.src.replace("_off", "_on");
                var status = '1';
            } else {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
                this.src = this.src.replace("_on", "_off");
                var status = '0';
            }
            $(this).toggleClass("on");
            
             var dataString ='&type=changestatusgroup&id='+vendor_id[1]+'&status='+status;
           // alert(dataString)
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'changestatusgroup'))?>',
                        data: dataString,
                success: function(j) {
                        window.location.replace("<?=$this->url(array('controller'=>'material','action'=>'groupmaster'))?>");
                        $('#mask').hide();
                }
               
     });
           
            
        });
        
         $( "#matgrp_form" ).submit(function( event ) {
            var category = $('select#category').val();
            var group_comp = $('#group_comp').val();
            var group_comp = group_comp.trim();
            var group_comp_char = $('#group_comp_char').val();
            var group_comp_char = group_comp_char.trim();
            
            if(category == '0'){
               $('#category').focus();
               return false;
            }
            if(group_comp == ''){
               $('#group_comp').focus();
               return false;
            }
            if(group_comp_char == ''){
               $('#group_comp_char').focus();
               return false;
            }
            
          });
    
     });
 </script>
 <?php echo $this->render('materiallist.phtml');  ?> 

<div class="span9" id="content">
     <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
    
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Material Sub Category</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#materiallist" class="listtab">Material Sub Category List</a></li>
  <li class="addstatus"><a href="#addstatus" class="contenttab">Add New Material Sub Category</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="materiallist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>Major Category</th>
                                                <th>Sub Category</th>
                                                 <th>Sub Category Code</th>
                                                <th>Action</th>
                                                <th>Approval</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->materialgroup as $value) { ?>
                                            <tr><td><?php echo $value[category] ?></td>
                                                <td><?php echo $value[group_comp] ?></td>
                                                <td><?php echo $value[group_comp_char] ?></td>
                                                <td>
<!--                                                    <a href="<?php echo $this->baseUrl();?>/admin/material/deletegroup/delete/<?php echo $value[id]; ?>" class="book_delete" style="cursor:pointer;"><?php echo 'DEL '; ?></a>-->
                                                    <a  class="viewgroup" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo ' VIEW'; ?></a>
                                                    <a  class="editgroup" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a></td>
                                               <td> <?php if($value[status] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php }  if($value[status] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php echo $value[id]; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                <?php } ?>
                                                </td>
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addstatus">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'material','action'=>'savematerialgroup'))?>" method="post" name="matgrp_form" id="matgrp_form">
        <input type="hidden" name="id" id="id" value="" class="inputDisabled">
       
          <div class="formvalue">
              <div class="form-left pull-left"><label for="firstname" class="required">Major Category:</label></div>
              <div class="form-right pull-left">
                  
                  <select class="materialgroup inputDisabled" name="category" id="category" required="true">
                        <option value="">Select</option>
                      <?php   foreach ($this->materialgroupcategory as $cat) { ?>
                                <option  value="<?php echo $cat[charac] ?>"><?php echo $cat[category] ?></option>
                       <?php } ?>
                    
                      
                     
                  </select>
              </div>
          </div>
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="group_char" class="required">Major Category Code:</label></div>
              <div class="form-right pull-left"><input type="text" name="group_char" id="group_char" value="" class="form-control" required="true" readonly></div>
          </div>
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="group_comp" class="required">Sub Category:</label></div>
              <div class="form-right pull-left"><input type="text" name="group_comp" id="group_comp" value="" class="form-control inputDisabled" onkeypress="return isAlphaSpace(event)" required="true" maxlength="20"></div>
          </div>
        <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="group_comp_char" class="required">Sub Category Code:</label></div>
              <div class="form-right pull-left"><input type="text" name="group_comp_char" id="group_comp_char" value="" class="form-control inputDisabled" required="true" onkeypress="return isAlpha(event)" maxlength="3" style="text-transform: uppercase;"></div>
          </div>
                             
        <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="group_desc" >Description:</label></div>
              <div class="form-right pull-left">
                  <!--<input type="text" name="group_desc" id="group_desc" value="" class="form-control inputDisabled">-->
                <textarea name="group_desc" id="group_desc" class="inputDisabled" rows='3' cols='5'></textarea>
          </div>
          </div>
          
          
<div id="button_div" class="clearfix span7" style="float: right;" >
<div class="span2" id="save_button">
 <input class='btn btn-primary' type="submit" name="deptregister" id="deptregister" value="Save" class="btn btn-default" />
</div>
 
<div class="span1" id="back_button">
    <a href="/../asteria/admin/material/groupmaster"><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
</div>
      </div>


</form>
      
      </div>
  
  
</div>
                                   
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   

    

</div>
 




