 <script type="text/javascript">
     
   $(document).ready(function(){
       
        
         $(document).on("click", ".addstatus", function(){
           $('#matgrpcate_form')[0].reset();
           $('#save_button').removeClass("hidden");
           $('.inputDisabled').removeAttr("readonly");
           $('#button_div').addClass("span7").removeClass("span9");
       });
       
          
                $(document).on("click", ".editgroupcategory", function(){
               $('#myTab a[href="#addstatus"]').tab('show');
                var id = $(this).attr("id");
             //   alert(id)
           var dataString ='&type=getgroup&id='+id;
            // alert(dataString);
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'getmaterialgroupcategory'))?>',
                        data: dataString,
                success: function(j) {
                   // alert(result);
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v);     
                    });
                    });
                    //$('div#addstatus').html(result);
                }
            });
         });
    
         
        $(document).on("click", ".imgswap", function(){
         var id = $(this).attr("id");
         var vendor_id = id.split("_"); 
         
            if ($(this).attr("class") == "imgswap") {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
                this.src = this.src.replace("_off", "_on");
                var status = '1';
            } else {
                $('#'+id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
                this.src = this.src.replace("_on", "_off");
                var status = '0';
            }
            $(this).toggleClass("on");
            
             var dataString ='&type=changestatusgroupcategory&vendorid='+vendor_id[1]+'&status='+status;
           // alert(dataString)
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'changestatusgroupcategory'))?>',
                        data: dataString,
                success: function(j) {
                    alert(result);
                    //$('div#addstatus').html(result);
                }
     });
           
            
        });
    
        
        $( "#matgrpcate_form" ).submit(function( event ) {
            var category = $('#category').val();
            var category = category.trim();
            var charac = $('#charac').val();
            var charac = charac.trim();
            
            if(category == ''){
               $('#category').focus();
               return false;
            }
            if(charac == ''){
               $('#charac').focus();
               return false;
            }
            
     });


    
     });
 </script>
  
 <?php echo $this->render('materiallist.phtml');  ?> 

<div class="span9" id="content">
    <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
    
    
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
        
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Material Major Category</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active"><a href="#materiallist">Material Major Category List</a></li>
  <li class="addstatus"><a href="#addstatus">Add New Material Major Category</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="materiallist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>Material Category</th>
                                                <th>Category Code</th>
<!--                                                <th>Status</th>-->
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->materialgroupcategory as $value) { ?>
                                            <tr><td><?php echo $value[category] ?></td>
                                                <td><?php echo $value[charac] ?></td>
                                                
<!--                                                    <a href="<?php echo $this->baseUrl();?>/admin/material/deletegroupcategory/delete/<?php echo $value[id]; ?>" class="book_delete" style="cursor:pointer;"><?php echo 'DEL '; ?></a>
                                                    <a  class="editgroupcategory" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a></td>-->
                <!--       Status     -->
<!--                                                <td>
                                                    <?php // if($value[status] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php // echo $value[id]; ?>" src="<?php // echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php// }  if($value[status] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php // echo $value[id]; ?>" src="<?php  // echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                <?php // } ?>
                                                        </td>-->
                                                
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addstatus">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'material','action'=>'savematerialgroupcategory'))?>" method="post" id="matgrpcate_form">
        <input type="hidden" name="id" id="id" value="" >
          
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="category" class="required">Material Major Category:</label></div>
              <div class="form-right pull-left"><input type="text" name="category" id="category" value="" class="form-control" required="true" maxlength="20"></div>
          </div>
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="charac" class="required">Major Category Code:</label></div>
              <div class="form-right pull-left"><input type="text" name="charac" id="charac" value="" class="form-control" onkeypress="return isAlpha(event)" required="true" maxlength="1" style="text-transform: uppercase;"></div>
          </div>
        
          
          
<div id="button_div" class="clearfix span7" style="float: right;" >
<div class="span2" id="save_button">
 <input class='btn btn-primary' type="submit" name="deptregister" id="deptregister" value="Save" class="btn btn-default" />
</div>

<div class="span1" id="back_button">
    <a href="/../asteria/admin/material/groupcategorymaster"><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
</div>
      </div>


</form>
      
      </div>
  
  
</div>
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   

    

</div>




