  <style>
     .DTTT_container{display:none;}
 </style>
<script type="text/javascript">
     
   $(document).ready(function(){
       
        
        $(document).on("click", "tbody tr td .imgswap", function() {
        var id = $(this).attr("id");
        var vendor_id = id.split("_");
        if ($(this).attr("class") == "imgswap") {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_on.png')
            this.src = this.src.replace("_off", "_on");
            var status = '1';
        } else {
            $('#' + id).attr('src', '<?php echo $this->baseUrl();?>/public/images/tick_off.png')
            this.src = this.src.replace("_on", "_off");
            var status = '0';
        }
        $(this).toggleClass("on");

        var dataString = '&type=changestatus&id=' + vendor_id[1] + '&status=' + status;

        $.ajax({
            type: "POST",
            url: '<?=$this->url(array('controller'=>'material','action'=>'changestatus'))?>',
            data: dataString,
            success: function(j) {
                
            }
        });
    });
    jQuery('.delete_method').click(function () {
     if(confirm("Are you sure you want to delete this?")){
     }
    else{
        return false;
    }
});
       $('.methodlist').click(function(){
        jQuery('#reset').trigger('click');
        $('.edit').html('Add Shipping Method');
         
           $('#save_button').removeClass("hidden");
           $('.inputDisabled').removeAttr("readonly");
             $('#name').removeAttr("disabled");
               $('#description').removeAttr("disabled");
            $('#button_div').addClass("span7").removeClass("span9");
       });
       
            $('.editmethod').click(function(){
                jQuery('#mask').show();
               $('#myTab a[href="#addmethod"]').tab('show');
           var id = $(this).attr("id");
           $('.edit').html('Edit Shipping Method');
        
           var dataString ='&edit-id='+id;
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'shipping'))?>',
                        data: dataString,
                success: function(j) {
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v);     
                    });
                    });
                  jQuery('#mask').hide();
                }
            });
         });
         
          $('.viewmethod').click(function(){
          jQuery('#mask').show();
               $('#myTab a[href="#addmethod"]').tab('show');
                var id = $(this).attr("id");
             $('.edit').html('View Shipping Method');
             $('#save_button').addClass("hidden");
             $('#button_div').addClass("span9").removeClass("span7");
           var dataString ='&edit-id='+id;
            $.ajax({
                type: "POST",
                url: '<?=$this->url(array('controller'=>'material','action'=>'shipping'))?>',
                        data: dataString,
                success: function(j) {
                    var json = $.parseJSON(j);
                    $(json).each(function(i,val){
                        $.each(val,function(k,v){
                              
                              $('#'+k).val(v); 
                                $('#'+k).attr("disabled",true);
                    });
                    });
                  jQuery('#mask').hide();
                }
            });
         });
         
         
          $( "#status_form" ).submit(function( event ) {
            var name = $('#name').val();
            var name = name.trim();
            var charac = $('#charac').val();
            var charac = charac.trim();
            var priority = $('#priority').val();
            var priority = priority.trim();
            
            if(name == ''){
               $('#name').focus();
               return false;
            }
            if(charac == ''){
               $('#description').focus();
               return false;
            }
          
            
          });
    
     });
 </script>
 <div class="span1"></div>

<div class="span10" id="content">
    
      <?php echo $this->render('globalmessage/globalmessage.phtml'); ?>
<!-- CLIENTS LIST-->
      
    <div class="row-fluid" style="height:525px;">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                <div class="navbar navbar-inner block-header">
                                    <div class="muted pull-left">Shipping Method</div>
                                    <div class="pull-right"><span class="badge badge-info"><?=$this->books1;?></span>

                                    </div>
                                </div>
                                 <div class="accordion block-content collapse in" id="accordion2">
  
                                  <ul class="nav nav-tabs" id="myTab">
  <li class="active methodlist"><a href="#methodlist">Shipping method List</a></li>
  <li class="addmethod"><a href="#addmethod" class="edit">Add Shipping method</a></li>
  </ul>
 
<div class="tab-content">
  <div class="tab-pane active" id="methodlist">
      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        <thead>
                                            <tr>
                                                <th>Shipping Method</th>
                                                <th>Shipping Method Description</th>
                                                 <th>Action</th>
                                                <th>Approval</th>
                                                </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->shipping as $value) { ?>
                                            <tr><td><?php echo $value[name] ?></td>
                                                <td><?php echo $value[description] ?></td>
                                              
                                               
                                                <td>
                                                    <a  class="viewmethod" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo 'VIEW'; ?></a>
                                                    <a  class="editmethod" id="<?php echo $value[id]; ?>" style="cursor:pointer;"><?php echo '/ EDIT'; ?></a>
                                                    <a href="<?php echo $this->baseUrl();?>/admin/material/shipping/delete/<?php echo $value[id]; ?>" class="delete_method" style="cursor:pointer;"><?php echo '/ DEL '; ?></a>
                                                    
                                                </td>
                                                 <td>
                                                <?php if($value['status'] == '0'){ ?>
                                                    <img class="imgswap" id="approval_<?php echo $value['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_off.png"/>
                                                    <?php }  if($value['status'] == '1'){ ?>
                                                    <img class="imgswap on" id="approval_<?php echo $value['id']; ?>" src="<?php echo $this->baseUrl();?>/public/images/tick_on.png"/>
                                                    <?php } ?>
                                                 </td>
                                                
                                            <?php  } ?>
                                            </tr>
                                            
                                        </tbody>
                                    </table>
  </div>
    
    
  <div class="tab-pane" id="addmethod">
      <form enctype="application/x-www-form-urlencoded" action="<?=$this->url(array('controller'=>'material','action'=>'shipping'))?>" method="post" id="method_form">
        <input type="hidden" name="id" id="id" value="" class="inputDisabled">
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="Name" class="required">Shipping Method:</label></div>
              <div class="form-right pull-left"><input onkeypress="return isAlphaSpace(event)" type="text" name="name" id="name" value="" maxlength="20" class="form-control inputDisabled" required="true"></div>
          </div>
          <div class="formvalue clearfix">
              <div class="form-left pull-left"><label for="Description" class="required">Description:</label></div>
              <div class="form-right pull-left"><input type="text" name="description" id="description" value="" maxlength="50" class="form-control inputDisabled" required="true"></div>
          </div>
         
          

<div id="button_div" class="clearfix span7" style="float: right;" >
<div class="span2" id="save_button">
 <input class='btn btn-primary' type="submit" name="save" id="deptregister" value="Save" class="btn btn-default" />
</div>
 
<div class="span1" id="back_button">
    <a href=""><input class='btn btn-primary' type="button" name="back" id="back" value="Back" class="btn btn-default" /></a>
</div>
    <input style="display:none;" type="reset" name="reset" id="reset" value="Reset" class="btn btn-primary">
      </div>

</form>
      
      </div>
  
  
</div>
 
<script>
  $(function () {
      $('#myTab a[href="#<?php echo $this->showid;?>"]').tab('show');
    $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
  })
</script>   
                                     
                                     
                                     
</div>
        
                            </div>
                            <!-- /block -->
                        </div>
                        
                    </div>
   

    

</div>




