
<!-- Mon compte Section -->
  <section id="login" class="section">
	<div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3><strong>Créez</strong> votre compte</h3>
		<p>Lorem ipsum dolor sit amet</p>
        <hr>       
      </div>
	  <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="service animated hiding" data-animation="fadeInUp" data-delay="0">
           <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-2x fa-stack-2x"></i>
            <i class="fa fa-trophy fa-stack-1x service-icon"></i>
          </span>
		  <h3>LOGIN</h3>
                
            
                    <div class="row-fluid" >
                        <div class="span3" id="content1" style="display:none;width: 33%;margin-left: 33.5%;margin-bottom: -20px;">

                        <div class="alert alert-error">	
<!--                            <button type="button" class="close" data-dismiss="alert">&times;</button>-->
                                <div id="kumar">
                        	</div></div></div></div>
          		    <br>
            <form name="login-form" id="login-form" method="POST" action="<?=$this->url(array('controller'=>'loginform','action'=>'logincheck'));?>">        
            <div class="form-group">
            <label class="col-md-4 col-sm-4 col-xs-12">Votre email :</label>
            <input class="col-md-4 col-sm-6 col-xs-6 form-login  input-small" type="text" placeholder="Il ne sera pas publié" id="email" name="email" required/>
		    <p class="clearfix"></p>
            </div>        
            <div class="form-group">                    
            <label class="col-md-4 col-sm-4 col-xs-12 ">Votre mot de passe :</label>
            <input class="col-md-4 col-sm-6 col-xs-6 form-login  input-small" id="password" name="password" placeholder="Your Password" required type="password" />
		    <p class="clearfix"></p>
            </div>        
<!--            <div class="text-left captcha col-md-offset-4 col-sm-offset-4 ">            
                <img src="<?php //echo $this->baseUrl();?>/public/clematix/images/recaptcha.png"> Add code from http://www.google.com/recaptcha
            </div>-->
            
            <input type="submit" id="create" name="create" value="Signin" class="btn-plein col-md-offset-0 col-sm-offset-0" style="margin-left:-25%;width:8%;"/>
         </form>
                            <p class="clearfix"></p>
                            <p style="margin-left:8%;"><a href="<?php echo $this->baseUrl();?>/signupform" >New User Click Here?</a>&#160;&#160;&#160;<a href="#forget-pass" class="forgot">Forgot password?</a></p>
        </div>
		
      </div>
	 </div>
      
      
    <div style="display:none;" id="f">
            <div id="forget-pass" style="text-align: justify;color: #fff;padding:10px; background:#535153;border-radius: 5px;">
              
                <p style="margin-left:34%;">Please Enter your email</p>
               <form id="forgot-form" action="<?=$this->url(array('controller'=>'loginform','action'=>'forgetpassword'));?>" method="POST" name="chat-form" novalidate="novalidate">
               <label class="col-md-4 col-sm-4 col-xs-12 ">Votre email :</label>
                    <input class="col-md-6 col-sm-6 col-xs-6 form-login  input-small" type="text" placeholder="Il ne sera pas publié" id="forgetemail" name="forgetemail" required="true"/>
		    <p class="clearfix"></p>
                    <label class="col-md-4 col-sm-4 col-xs-12"></label>
                    <input type="submit" id="forgot-submit" name="forgot-submit" value="submit" class="btn-plein col-md-offset-6 col-sm-offset-6" />
               </form>
            </div></div>
  </section>
<style>    .alert-error {
  color: #b94a48;
  background-color: #f2dede;
  border-color: #eed3d7;
}</style>
  <!-- End Bureaux Section -->
  
  
  <script>
        $("#forgot-form").validate({
    
        rules: {
            
            forgetemail: {
                required: true,
                email: true
            },
        },
        
        // Specify the validation error messages
        messages: {
            
            forgetemail: "Please enter a valid email address",
//            agree: "Please accept our policy"
        },
      
        submitHandler: function(form) {
           var url = $(form).attr('action');
      $.ajax({
        type: "POST",
        url: url,
        data: $(form).serialize(),
        // serializes the form's elements.
        
        success: function(data)
        {
        
           if(data==0)
           {
               $('#forget-pass').html('<br/><center>Please Enter valid email</center><br/> ');
              
               
           }
           else if(data==1)
           {
               $('#forget-pass').html('<br/><center>Mail sent.Please check your email</center><br/>');
          
           }
            
        }
      });
        }
        
    });
 
 
      $(function(){
       
       
      $(".forgot").colorbox({inline:true, width:"50%",height:"50%"});
  });
           </script>