
      <div class="navbar-header col-md-offset-1">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?=$this->url(array('controller'=>'createbook','action'=>'index'));?>" id="logo"><img src="/clematixdigital/public/clematix/images/logo.png" alt="Clematix"/></a>
      </div>

<!-- Mon compte Section -->
  <section id="login" class="section" style="margin-top: 40px;">
	<div class="container">    
      
	<div class="col-md-12 col-sm-12 col-xs-12">
        <div class="service animated hiding" data-animation="fadeInUp" data-delay="0">
           <span class="fa-stack fa-4x">
            <i class="fa fa-circle fa-2x fa-stack-2x"></i>
            <i class="fa fa-trophy fa-stack-1x service-icon"></i>
          </span>
		  <h3>PASSWORD CHANGE</h3>
                
            
                    <div class="row-fluid" >
                        <div class="span3" id="content1" style="display:none;width: 50%;margin-left: 33.5%;margin-bottom: -20px;">

                        <div class="alert alert-error">	
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <div id="kumar">
                        	</div></div></div></div>
          		    <br>
            <form name="passchange" id="passchange" method="POST" action="<?=$this->url(array('controller'=>'loginform','action'=>'pcupdate'));?>">        
            <div class="form-group">
            
            <input class="col-md-4 col-sm-6 col-xs-6 form-login input-small col-md-offset-4" type="text" value="<?php echo $this->passchange;?>" id="pcuemail" name="pcuemail" required="true" readonly/>
		    <p class="clearfix"></p>
            </div>        
            <div class="form-group">                    
            
            <input class="col-md-4 col-sm-6 col-xs-6 form-login input-small col-md-offset-4" id="pcupassword" name="pcupassword" placeholder="Password" required="true" type="password" />
		    <p class="clearfix"></p>
            </div>       
                <div class="form-group">                    
            
            <input class="col-md-4 col-sm-6 col-xs-6 form-login input-small col-md-offset-4" id="pcucpassword" name="pcucpassword" placeholder="ConfirmPassword" required="true" type="password" />
		    <p class="clearfix"></p>
            </div> 
           <div class="form-group">   
            <input type="hidden" id="changekey" name="changekey" value="<?php echo $this->changekey;?>" class="btn-plein" />
            <input type="submit" id="create" name="create" value="Change" class="btn-plein" />
           </div>
         </form>
                          
        </div>
		
      </div>
	 </div>
      
  </section>

<style>    
 .alert-error 
  {
  color: #b94a48;
  background-color: #f2dede;
  border-color: #eed3d7;
  }
</style>
  <!-- End Bureaux Section -->
  
  
  <script>
      
      
      $("#passchange").validate({
        
        errorPlacement: function(error, element) {},
        highlight: function(element, errorClass) {        
            $(element).parent().removeClass('success').addClass('error');
        },
        unhighlight: function(element, errorClass) {
            $(element).parent().removeClass('error').addClass('success');
        },
        
        rules: {
            
            pcuemail: {
                required: true,
                email: true
            },
            pcupassword: {
                required: true,
                minlength:6
                
            },
            pcucpassword: {
                required: true,
                equalTo: "#pcupassword"
            }
        },
        
        // Specify the validation error messages
       
        
        submitHandler: function(form) {
           var url = $(form).attr('action');
      $.ajax({
        type: "POST",
        url: url,
        data: $(form).serialize(), // serializes the form's elements.
        success: function(data)
        {     
           if(data==1)
           {
                $('#kumar').html('Your password reset successfully');
                $('.span3').show();
              
               
           }
           else if(data==0)
           {
               $('#kumar').html('Problem occuring in change Your password<br/> Re enter your email address');
               $('.span3').show();
             
           }
            
        }
      });
     
           
        }
    });
  
      $(function()
      {
        $("footer").hide();
        $("header").hide();
        $("aside").hide();
        $(".forgot").colorbox({inline:true, width:"50%",height:"50%"});
      });
           </script>