<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>My Zend Framework Quickstart Application</title>
   <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>  
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Welcome to Chat Room</b>
    </div>
    
</div>

<?php echo $this->layout()->content ?>

</body>
</html>