<?php foreach($this->entries as $entry): ?>
    <form method="post" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'viewcustomerchat')) ?>">
        <label>
            <input type="hidden" name="sessId" value="<?php echo $entry->sessId; ?>" />
            <?php echo $entry->sessId; ?>
        </label>
        <input type="submit" name="submit" value="Open chat" />
    </form>
<?php endforeach; ?>
