
<script src="<?php echo $this->baseUrl();?>/public/js/jquery.colorbox.js"></script>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/colorbox.css" />

<?php 
   $storage = new Zend_Auth_Storage_Session();
   $data = $storage->read();
?>

<header class="navbar navbar-default topnav navbar-fixed-top" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="./" id="logo"><img src="<?php echo $this->baseUrl();?>/public/clematix/images/logo.png" alt="Clematix"/></a>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav navbar-right nav-tabs" id="nav">
          <li><a href="<?php echo $this->baseUrl();?>/index">Home</a></li>
          <li><a href="<?php echo $this->baseUrl();?>/aboutus">About us</a></li>
          <li><a href="<?php echo $this->baseUrl();?>/contact">Contact us</a></li> 
          <?php if($data->uname) { ?>
          <li><a  href="<?php echo $this->baseUrl();?>/myaccount">My account</a></li>
                       
          <li style="margin-top: 10px;
              margin-left: 20px;
              margin-right: -30px; display: inline;"><p>Welcome <b><?=$data->uname?></b>
              <a href="<?php echo $this->url(array('controller'=>'signupform', 'action'=>'logout')) ?>" style="color:#641e73;">&nbsp;&nbsp;Logout</a></p></li>
          
          <?php } else {?>
          <li class="dropdown"><a class="dropdown-toggle"data-toggle="dropdown" href="#">My account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->baseUrl();?>/loginform">Login</a></li>
                  <li><a href="<?php echo $this->baseUrl();?>/signupform">Signup</a></li>
              </ul></li> <?php }?>

        </ul>
          
      </div>
    </div>
  </header>
  <!-- End Header --> 