<div class="line3"></div>
<div class="box2"><div class="box2_text">You are currently browsing the <br />
archives for the Est eligendi<br />
optioco amet sreen category.</div></div>
<div class="leftcat">
<div class="cat"><b>Categories</b></div>


        	
            <ul>
              <li><a href="#" title="#">At vero eos et accu sereater</a></li>
              <li><a href="#" title="#">At vero eos et accu sereatera</a></li>
              <li><a href="#" title="#">Est eligendi optioco amet sreen</a></li>
              <li><a href="#" title="#">Etusam Iustdigne imirtehaslelus</a></li>
              <li><a href="#" title="#">Leliq cum soluno aters</a></li>
              <li><a href="#" title="#">Que sunt solun porta</a></li>
              <li><a href="#" title="#">Quo minus at veter auetyen</a></li>
				</ul>
<div class="line"></div>

	</div>
    <div class="left">	
			<div class="cat"><b>Archives</b></div>
<div class="line"></div>		  
		   				    <ul><li><a href="#" title="#"><b>August 2009</b></a></li>
							<li><a href="#" title="#"><b>July 2009</b></a></li>
							<li><a href="#" title="#"><b>June 2009</b></a></li>
	<li><a href="#" title="#"><b>April 2009</b></a></li></ul>
    <div class="line"></div></div>
    <div class="left2">			
			<div class="cat"><b>Blogroll</b></div><div class="line"></div>
            <ul>
<li><a href="#" title="#"><b>Development Blog</b></a></li>
							<li><a href="#" title="#"><b>Documentation</b></a></li>
							<li><a href="#" title="#"><b>Plugins</b></a></li>
							<li><a href="#" title="#"><b>Suggest Ideas</b></a></li>
                            <li><a href="#" title="#"><b>Support Forum</b></a></li>
							<li><a href="#" title="#"><b>Themes</b></a></li>
    <li><a href="#" title="#"><b>WordPress Planet</b></a></li></ul>
    <div class="line"></div></div>
    <div class="left">	
            <div class="cat"><b>Meta</b></div>
            <div class="line"></div>
			  <ul>
              				<li class="li3"><a href="#" title="#"><b>Log in</b></a></li>
							<li class="li3"><a href="#" title="#"><b>W3C Page</b></a></li>
							<li class="li3"><a href="#" title="#"><b>XFN</b></a></li>
	<li><a href="#" title="#"><b>WordPress</b></a></li></ul>
    <div class="line"></div>
        <div class="line"></div>
        <div class="line2"></div>
        

</div>