<div id="container">
    <div id="topmenu">
				<div class="rights"></div>
				<div class="lefts">
                <ul>
							<li><a href="#" title="home">Home</a></li>
							<li><a href="#" title="about">About</a></li>
							<li><a href="#" title="service">Service</a></li>
							<li><a href="#" title="solution">Solution</a></li>
							<li><a href="<?php echo $this->baseUrl();?>/contact" title="contact">Contact</a></li>
				
				</ul></div>
	</div></div>