<?php 
    if($this->values->date >0)
    {
    //Date    
    $eff_date = new Zend_Date($this->values->date, 'dd-mm-yyyy', 'en');
    $eff_date = $eff_date->get('dd/mm/yyyy'); 
    //Start and End Time
    
    } 
    else { 
    $eff_date='';
    
    } 
    
    
?>



<div class="row">

            

          
           
            <div class="span9" id="content">
            <div class="row-fluid">
                  <?php
                    if(isset($this->errorMessage)){
                    ?>
                    <div class="alert alert-error">
                            <button class="close" data-dismiss="alert">&times;</button>
                            <strong>Error!</strong> <?=$this->errorMessage;?>.
                    </div>        

                     <?php } ?>
                        	<div class="navbar">
                            	<div class="navbar-inner">
	                                <ul class="breadcrumb">
	                                    <i class="icon-chevron-left hide-sidebar"><a href='#' title="Hide Sidebar" rel='tooltip'>&nbsp;</a></i>
	                                    <i class="icon-chevron-right show-sidebar" style="display:none;"><a href='#' title="Show Sidebar" rel='tooltip'>&nbsp;</a></i>
	                                    <li>
	                                        <a href="<?=$this->url(array('module'=>'admin','controller'=>'auth','action'=>'home'))?>">Dashboard</a> <span class="divider">/</span>	
	                                    </li>
	                                    
	                                    <li class="active">Timesheet</li>
	                                </ul>
                            	</div>
                        	</div>
                    	</div>
                
                
                
                   <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            <div class="navbar navbar-inner block-header">
                                <div class="muted pull-left">Projects</div>
                            </div>
                            <div class="block-content collapse in">
                                <div class="span12">
                                    <form action="" id="contact-form" class="form-horizontal" method="post" enctype="multipart/form-data">
                                      <fieldset>
                                        <legend>Project Input</legend>
                                        
                                         <div class="control-group">
                                          <label class="control-label" for="date01">Project Name</label>
                                          <div class="controls">
                                              
                                            <input type="text" class="input-xlarge" id="name" name="name" value="<?=$this->values->name?>" placeholder="Project Name">
                                            
                                          </div>
                                        </div>
                                        
                                          <div class="control-group">
                                          <label class="control-label" for="select01">Select Client</label>
                                          <div class="controls">
                                            <select name="client" id="client" class="chzn-select">
                                              <option>Select</option>
                                              <?php
                                                for($i=0;$i<count($this->clients);$i++){
                                                ?>
                                                    <option value="<?=$this->clients[$i]['id']?>" <?php if($this->clients[$i]['id'] == $this->values->clientid){ echo "selected=selected"; } ?>>
                                                    <?=$this->clients[$i]['firstname'].' '.$this->clients[$i]['lastname']?>
                                                    </option>
                                                <?php
                                                }
                                                ?>
                                            </select>
                                          </div>
                                        </div>
                                        
                                        <div class="control-group">
                                          <label class="control-label" for="date01">Date input</label>
                                          <div class="controls">
                                              
                                            <input type="text" class="input-xlarge datepicker" id="date" name="date" value="<?=$eff_date?>" placeholder="dd/mm/yyyy">
                                            <p class="help-block">Select Date from picker you want to update in Time Sheet</p>
                                          </div>
                                        </div>
                                        
                                      
                                        
                                         <div class="control-group">
                                        <label class="control-label" for="email">Budget Hour(s)</label>
                                        <div class="controls">
                                        <input type="text" class="input-xlarge" name="totalhour" id="totalhour" value="<?=$this->values->totalhour?>" placeholder="hours">
                                        </div>
                                        </div>
                                       
                                         
                                        <div class="form-actions">
                                            <input type="hidden" name="id" value="<?=$this->values->id?>">
                                          <button type="submit" class="btn btn-primary" name="Submit">Save changes</button>
                                          <button type="reset" class="btn">Cancel</button>
                                        </div>
                                      </fieldset>
                                    </form>

                                </div>
                            </div>
                        </div>
                        <!-- /block -->
                    </div>
                
                
            
           
            </div>
            
            
            
            