<div class="span9" id="content">
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Bootstrap dataTables</div>
                
                <div class="muted pull-right">
                    
                    <a href="<?=$this->url(array('module'=>'admin','controller'=>'actual','action'=>'addproject','id'=>null))?>" class="">Add Project</a>
<div id="myModal" class="modal hide">
											<div class="modal-header">
												<button data-dismiss="modal" class="close" type="button">&times;</button>
												<h3>Modal header</h3>
											</div>
											<div class="modal-body">
												<p>Modal Example Body</p>
											</div>
										</div>
                                </div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                                                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                                                                <thead>
                                                                <tr>
                                                                    <th>Name</th>
                                                                    <th>Date</th>
                                                                    <th>client</th>
                                                                    <th>Budget in Hour(s)</th>
                                                                    <th>Action</th>
                                                                </tr>
                                                                </thead>
                                                               <tbody>
                                                                    <?php
                                                                    for($i=0;$i<count($this->entries);$i++){
                                                                          $date = new Zend_Date($this->entries[$i]['date']);
                                                                          $eff_date = new Zend_Date($this->entries[$i]['date'], 'dd-mm-yyyy', 'en');
                                                                          $eff_date = $eff_date->get('dd/mm/yyyy');
                                                                          
                                                                          
                                                                         
                                                                    ?>
                                                                    <tr>
                                                                    <td><?=$this->entries[$i]['name']?></td>
                                                                    <td><?=$eff_date?></td>
                                                                    <td><?=$this->entries[$i]['firstname'].' '.$this->entries[$i]['lastname']?></td>
                                                                    <td><?=$this->entries[$i]['totalhour']?></td>
                                                                    <td><ul class="the-icons clearfix"><a href="<?=$this->url(array('module'=>'admin','controller'=>'actual','action'=>'addproject','id'=>$this->entries[$i]['id']))?>"><li><i class="icon-edit"></i> </li></a></ul></td>

                                                                   </tr>
                                                                <?php } ?>
                                                                </tbody>



                                                        </table>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>


</div>                    


                    