<div class="span9" id="content">
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Bootstrap dataTables</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                                                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
                                                                <thead>
                                                                <tr>
                                                                    <th>Name</th>
                                                                    <th>Project</th>
                                                                    <th>Date</th>
                                                                    <th>Hour(s)</th>
                                                                    <th>Week</th>
                                                                    <th>Action</th>
                                                                </tr>
                                                                </thead>
                                                               <tbody>
                                                                    <?php

                                                                    
 
                                                                   
                                                                    
                                                                    
                                                                    
                                                                    
                                                                     for($i=0;$i<count($this->entries);$i++){
                                                                          $date = new Zend_Date($this->entries[$i]['date']);
                                                                          $eff_date = new Zend_Date($this->entries[$i]['date'], 'dd-mm-yyyy', 'en');
                                                                          $eff_date = $eff_date->get('dd/mm/yyyy');
                                                                          
                                                                          
                                                                          $week= $date->get(Zend_Date::WEEK);
                                                                          
                                                                          $start = $this->entries[$i]['date'].' '.$this->entries[$i]['start'];
                                                                          $end = $this->entries[$i]['date'].' '.$this->entries[$i]['end'];
                                                                          
                                                                          $dateStartZD = new Zend_Date($end);
                                                                        $dateEndZD = new Zend_Date($start);
                                                                        $dateStartZD->sub($dateEndZD);
                                                                        $hour = $dateStartZD->getTimestamp() / (60 * 60 );
                                                                    ?>
                                                                    <tr>
                                                                    <td><?=$this->entries[$i]['firstname']?>&nbsp<?=$this->entries[$i]['lastname']?></td>
                                                                    <td><?php if($this->entries[$i]['catname'] != '') { echo $this->entries[$i]['name']; } else { echo $this->entries[$i]['catname']; } ?></td>
                                                                    <td><?=$eff_date?></td>
                                                                    <td><?=$hour?></td>
                                                                    <td><?=$week?></td>
                                                                    <td><ul class="the-icons clearfix"><a href="<?=$this->url(array('module'=>'admin','controller'=>'actual','action'=>'index','id'=>$this->entries[$i]['id']))?>"><li><i class="icon-edit"></i> </li></a></ul></td>

                                                                   </tr>
                                                                <?php } ?>
                                                                </tbody>



                                                        </table>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>


</div>                    


                    