<!-- Mon compte Section -->


  <section id="account" class="section">
	<div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3>Mon <strong>compte</strong></h3>
               
		<p>Retrouvez toutes vos informations et vos commandes</p>
        <hr>       
      </div>
            
	  
	  <div class="title col-md-6 col-sm-6 col-xs-12">
        <div class="row-fluid">
                        <div class="span12">
                            <!-- block -->
                            <div class="block">
                                
                                <div class="block-content collapse in">
                                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" id="example">
                                        
                                        
                                            
                                        <tbody>
                                           <tr>
                                               <td>Audio Clip</td>
                                                <td><?php echo $this->orderdetails['audio']; ?></td>
                                                
                                            </tr>
                                            <tr>
                                               
                                                <td>Video Clip</td>
                                                <td><?php echo $this->orderdetails['video']; ?></td>
                                           
                                            </tr>
                                            <tr>
                                               
                                                <td>360 view</td>
                                                <td><?php echo $this->orderdetails['view360']; ?></td>
                                              
                                            </tr>
                                            <tr>
                                           
                                                <td>slides</td>
                                                <td><?php echo $this->orderdetails['slides']; ?></td>
                                              
                                            </tr>
                                            <tr>
                                             
                                                <td>Flash & Animation</td>
                                                <td><?php echo $this->orderdetails['flash']; ?></td>
                                                
                                            </tr>
                                            <tr>
                                                
                                                <td>Multiple choice Question</td>
                                                <td><?php echo $this->orderdetails['mulq']; ?></td>
                                              
                                            </tr>
                                            <tr>
                                                
                                                <td>Read Aloud</td>
                                                <td><?php echo $this->orderdetails['readaloud']; ?></td>
                                              
                                            </tr>
                                            <tr>
                                                
                                                
                                                <td>Total Page</td>
                                                <td><?php echo $this->orderdetails['totalpage']; ?></td>
                                               
                                            </tr>
                                            <tr>
                                                
                                                
                                                <td>Estimated Price</td>
                                                <td><?php echo $this->orderdetails['estprice']; ?></td>
                                            
                                            </tr>
                                            <tr>
                                                
                                                
                                                <td>Input Files</td>
                                                <td><?php echo $this->orderdetails['input']; ?>
                                                </td>
                                               
                                            </tr>
                                            
                                            
                                            
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- /block -->
                        </div>
        </div>
      </div>
            
            
	 </div>
  </section>
  <!-- End Bureaux Section -->
  
  
  
 