 <section id="home">
    <div class="container">
      <div class="hero">
	    <img src="<?php echo $this->baseUrl();?>/public/clematix/images/logo_big.png" alt="Clematix"/>
        <hr>
        <!-- Home Slider -->
        <div class="home-slider">
          <ul class="slides">
            <li>
				<h1>Quand tout va bien, l'optimisme est une sottise<br />Quand tout va mal, c’est un devoir</h1>
				<p>André Frossard</p>
			</li>
          </ul>
        </div>
        <!-- End Home Slider -->               
        <hr>
        
      </div>
    </div>
  </section>
  <!-- End Home Section -->

  <!-- About Section -->  
  <section id="about" class="section about-us">
    <div class="container">    
      <div class="title col-md-8 col-sm-10 col-xs-12">
        <h3>A <strong>propos</strong></h3>
        <hr>        
      </div>
	  <!-- About Text -->
      <p class="about-text"></p>
	</div>
  </section>
  <!-- End About Section -->
  
  <!-- Bureaux Section -->
<!--  <section id="bureaux" class="section coordonnees">
	<div class="container">    
      <div class="title col-md-10 col-sm-10 col-xs-12">
        <h3>Nos coordonnées <strong>complétes</strong></h3>
        <hr>       
      </div>
	  <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="team animated hiding" data-animation="fadeInUp" data-delay="0">
          <div class="team-photo" id="googleMapfrance">
            <img src="/public/clematix/images/contact/carte_france.jpg" alt="">
          </div>
          <div class="team-inner">
			<h5>France</h5>
            <p><br />10, Rue Lamartine<br />
			78100 Saint-Germain-en-Laye<br />
			<br />+ 33 6 71 13 76 33<br /><br /></p>
          </div>          
        </div>
      </div>
	  <div class="col-md-6 col-sm-6 col-xs-12">
        <div class="team animated hiding" data-animation="fadeInUp" data-delay="0">
          <div class="team-photo" id="googleMapindia">
            <img src="/public/clematix/images/contact/carte_india.jpg" alt="">
          </div>
          <div class="team-inner">
			<h5>India</h5>
            <p>42/1, 3rd floor, Ramprabha Towers,<br />
			Shanti Nagar,<br />
			Denkanikottai Main Road,<br />
			Hosur, Tamil Nadu, Pin 635109<br />
			<br />+ 91 4344 226232</p>
          </div>          
        </div>
      </div>
	 </div>
  </section>-->
  <!-- End Bureaux Section -->
  
  
  
  
  